//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 04:23:17 PM IST 
//


package ConsumerFinancing.equifax.models.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for association-informationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="association-informationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="latest-start-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="latest-ceased-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="is-serious-credit-infringement" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="sci-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="default-association-start-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="default-association-cease-date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="additional-data-fields" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}additional-data-fieldsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}disputeGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "association-informationType", propOrder = {
    "latestStartDate",
    "latestCeasedDate",
    "isSeriousCreditInfringement",
    "sciDate",
    "defaultAssociationStartDate",
    "defaultAssociationCeaseDate",
    "additionalDataFields"
})
public class AssociationInformationType {

    @XmlElement(name = "latest-start-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar latestStartDate;
    @XmlElement(name = "latest-ceased-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar latestCeasedDate;
    @XmlElement(name = "is-serious-credit-infringement")
    protected Boolean isSeriousCreditInfringement;
    @XmlElement(name = "sci-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar sciDate;
    @XmlElement(name = "default-association-start-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar defaultAssociationStartDate;
    @XmlElement(name = "default-association-cease-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar defaultAssociationCeaseDate;
    @XmlElement(name = "additional-data-fields")
    protected AdditionalDataFieldsType additionalDataFields;
    @XmlAttribute(name = "is-disputed")
    protected Boolean isDisputed;
    @XmlAttribute(name = "dispute-reported-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar disputeReportedDate;
    @XmlAttribute(name = "dispute-code")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String disputeCode;

    /**
     * Gets the value of the latestStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLatestStartDate() {
        return latestStartDate;
    }

    /**
     * Sets the value of the latestStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLatestStartDate(XMLGregorianCalendar value) {
        this.latestStartDate = value;
    }

    /**
     * Gets the value of the latestCeasedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLatestCeasedDate() {
        return latestCeasedDate;
    }

    /**
     * Sets the value of the latestCeasedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLatestCeasedDate(XMLGregorianCalendar value) {
        this.latestCeasedDate = value;
    }

    /**
     * Gets the value of the isSeriousCreditInfringement property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsSeriousCreditInfringement() {
        return isSeriousCreditInfringement;
    }

    /**
     * Sets the value of the isSeriousCreditInfringement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsSeriousCreditInfringement(Boolean value) {
        this.isSeriousCreditInfringement = value;
    }

    /**
     * Gets the value of the sciDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSciDate() {
        return sciDate;
    }

    /**
     * Sets the value of the sciDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSciDate(XMLGregorianCalendar value) {
        this.sciDate = value;
    }

    /**
     * Gets the value of the defaultAssociationStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDefaultAssociationStartDate() {
        return defaultAssociationStartDate;
    }

    /**
     * Sets the value of the defaultAssociationStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDefaultAssociationStartDate(XMLGregorianCalendar value) {
        this.defaultAssociationStartDate = value;
    }

    /**
     * Gets the value of the defaultAssociationCeaseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDefaultAssociationCeaseDate() {
        return defaultAssociationCeaseDate;
    }

    /**
     * Sets the value of the defaultAssociationCeaseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDefaultAssociationCeaseDate(XMLGregorianCalendar value) {
        this.defaultAssociationCeaseDate = value;
    }

    /**
     * Gets the value of the additionalDataFields property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalDataFieldsType }
     *     
     */
    public AdditionalDataFieldsType getAdditionalDataFields() {
        return additionalDataFields;
    }

    /**
     * Sets the value of the additionalDataFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalDataFieldsType }
     *     
     */
    public void setAdditionalDataFields(AdditionalDataFieldsType value) {
        this.additionalDataFields = value;
    }

    /**
     * Gets the value of the isDisputed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDisputed() {
        return isDisputed;
    }

    /**
     * Sets the value of the isDisputed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDisputed(Boolean value) {
        this.isDisputed = value;
    }

    /**
     * Gets the value of the disputeReportedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDisputeReportedDate() {
        return disputeReportedDate;
    }

    /**
     * Sets the value of the disputeReportedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDisputeReportedDate(XMLGregorianCalendar value) {
        this.disputeReportedDate = value;
    }

    /**
     * Gets the value of the disputeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisputeCode() {
        return disputeCode;
    }

    /**
     * Sets the value of the disputeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisputeCode(String value) {
        this.disputeCode = value;
    }

}
