//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 04:23:17 PM IST 
//


package ConsumerFinancing.equifax.models.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for commercial-credit-fileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="commercial-credit-fileType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="file-notes" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="file-note" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}file-noteType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="credit-enquiries" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="credit-enquiry" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}credit-enquiryType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="accounts" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="account" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}commercial-credit-accountType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="messages" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}messagesType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "commercial-credit-fileType", propOrder = {
    "fileNotes",
    "creditEnquiries",
    "accounts",
    "messages"
})
public class CommercialCreditFileType {

    @XmlElement(name = "file-notes")
    protected CommercialCreditFileType.FileNotes fileNotes;
    @XmlElement(name = "credit-enquiries")
    protected CommercialCreditFileType.CreditEnquiries creditEnquiries;
    protected CommercialCreditFileType.Accounts accounts;
    protected MessagesType messages;

    /**
     * Gets the value of the fileNotes property.
     * 
     * @return
     *     possible object is
     *     {@link CommercialCreditFileType.FileNotes }
     *     
     */
    public CommercialCreditFileType.FileNotes getFileNotes() {
        return fileNotes;
    }

    /**
     * Sets the value of the fileNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommercialCreditFileType.FileNotes }
     *     
     */
    public void setFileNotes(CommercialCreditFileType.FileNotes value) {
        this.fileNotes = value;
    }

    /**
     * Gets the value of the creditEnquiries property.
     * 
     * @return
     *     possible object is
     *     {@link CommercialCreditFileType.CreditEnquiries }
     *     
     */
    public CommercialCreditFileType.CreditEnquiries getCreditEnquiries() {
        return creditEnquiries;
    }

    /**
     * Sets the value of the creditEnquiries property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommercialCreditFileType.CreditEnquiries }
     *     
     */
    public void setCreditEnquiries(CommercialCreditFileType.CreditEnquiries value) {
        this.creditEnquiries = value;
    }

    /**
     * Gets the value of the accounts property.
     * 
     * @return
     *     possible object is
     *     {@link CommercialCreditFileType.Accounts }
     *     
     */
    public CommercialCreditFileType.Accounts getAccounts() {
        return accounts;
    }

    /**
     * Sets the value of the accounts property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommercialCreditFileType.Accounts }
     *     
     */
    public void setAccounts(CommercialCreditFileType.Accounts value) {
        this.accounts = value;
    }

    /**
     * Gets the value of the messages property.
     * 
     * @return
     *     possible object is
     *     {@link MessagesType }
     *     
     */
    public MessagesType getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessagesType }
     *     
     */
    public void setMessages(MessagesType value) {
        this.messages = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="account" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}commercial-credit-accountType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "account"
    })
    public static class Accounts {

        @XmlElement(required = true)
        protected List<CommercialCreditAccountType> account;

        /**
         * Gets the value of the account property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the account property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAccount().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CommercialCreditAccountType }
         * 
         * 
         */
        public List<CommercialCreditAccountType> getAccount() {
            if (account == null) {
                account = new ArrayList<CommercialCreditAccountType>();
            }
            return this.account;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="credit-enquiry" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}credit-enquiryType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "creditEnquiry"
    })
    public static class CreditEnquiries {

        @XmlElement(name = "credit-enquiry", required = true)
        protected List<CreditEnquiryType> creditEnquiry;

        /**
         * Gets the value of the creditEnquiry property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the creditEnquiry property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCreditEnquiry().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CreditEnquiryType }
         * 
         * 
         */
        public List<CreditEnquiryType> getCreditEnquiry() {
            if (creditEnquiry == null) {
                creditEnquiry = new ArrayList<CreditEnquiryType>();
            }
            return this.creditEnquiry;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="file-note" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}file-noteType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fileNote"
    })
    public static class FileNotes {

        @XmlElement(name = "file-note", required = true)
        protected List<FileNoteType> fileNote;

        /**
         * Gets the value of the fileNote property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fileNote property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFileNote().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link FileNoteType }
         * 
         * 
         */
        public List<FileNoteType> getFileNote() {
            if (fileNote == null) {
                fileNote = new ArrayList<FileNoteType>();
            }
            return this.fileNote;
        }

    }

}
