//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 04:23:17 PM IST 
//


package ConsumerFinancing.equifax.models.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * Enumerated complexType for ISO 3166-1 alpha-3	country codes
 * 
 * <p>Java class for countryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="countryType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd&gt;countryCodeEnumType"&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "countryType", propOrder = {
    "value"
})
public class CountryType {

    @XmlValue
    protected CountryCodeEnumType value;

    public CountryType() {
    }

    public CountryType(CountryCodeEnumType value) {
        this.value = value;
    }

    /**
     * Enumeration of ISO 3166-1 alpha-3 country codes
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeEnumType }
     *     
     */
    public CountryCodeEnumType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeEnumType }
     *     
     */
    public void setValue(CountryCodeEnumType value) {
        this.value = value;
    }

}
