//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 04:23:17 PM IST 
//


package ConsumerFinancing.equifax.models.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for countryCodeEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="countryCodeEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="ABW"/&gt;
 *     &lt;enumeration value="AFG"/&gt;
 *     &lt;enumeration value="AGO"/&gt;
 *     &lt;enumeration value="AIA"/&gt;
 *     &lt;enumeration value="ALA"/&gt;
 *     &lt;enumeration value="ALB"/&gt;
 *     &lt;enumeration value="AND"/&gt;
 *     &lt;enumeration value="ARE"/&gt;
 *     &lt;enumeration value="ARG"/&gt;
 *     &lt;enumeration value="ARM"/&gt;
 *     &lt;enumeration value="ASM"/&gt;
 *     &lt;enumeration value="ATA"/&gt;
 *     &lt;enumeration value="ATF"/&gt;
 *     &lt;enumeration value="ATG"/&gt;
 *     &lt;enumeration value="AUS"/&gt;
 *     &lt;enumeration value="AUT"/&gt;
 *     &lt;enumeration value="AZE"/&gt;
 *     &lt;enumeration value="BDI"/&gt;
 *     &lt;enumeration value="BEL"/&gt;
 *     &lt;enumeration value="BEN"/&gt;
 *     &lt;enumeration value="BES"/&gt;
 *     &lt;enumeration value="BFA"/&gt;
 *     &lt;enumeration value="BGD"/&gt;
 *     &lt;enumeration value="BGR"/&gt;
 *     &lt;enumeration value="BHR"/&gt;
 *     &lt;enumeration value="BHS"/&gt;
 *     &lt;enumeration value="BIH"/&gt;
 *     &lt;enumeration value="BLM"/&gt;
 *     &lt;enumeration value="BLR"/&gt;
 *     &lt;enumeration value="BLZ"/&gt;
 *     &lt;enumeration value="BMU"/&gt;
 *     &lt;enumeration value="BOL"/&gt;
 *     &lt;enumeration value="BRA"/&gt;
 *     &lt;enumeration value="BRB"/&gt;
 *     &lt;enumeration value="BRN"/&gt;
 *     &lt;enumeration value="BTN"/&gt;
 *     &lt;enumeration value="BVT"/&gt;
 *     &lt;enumeration value="BWA"/&gt;
 *     &lt;enumeration value="CAF"/&gt;
 *     &lt;enumeration value="CAN"/&gt;
 *     &lt;enumeration value="CCK"/&gt;
 *     &lt;enumeration value="CHE"/&gt;
 *     &lt;enumeration value="CHL"/&gt;
 *     &lt;enumeration value="CHN"/&gt;
 *     &lt;enumeration value="CIV"/&gt;
 *     &lt;enumeration value="CMR"/&gt;
 *     &lt;enumeration value="COD"/&gt;
 *     &lt;enumeration value="COG"/&gt;
 *     &lt;enumeration value="COK"/&gt;
 *     &lt;enumeration value="COL"/&gt;
 *     &lt;enumeration value="COM"/&gt;
 *     &lt;enumeration value="CPV"/&gt;
 *     &lt;enumeration value="CRI"/&gt;
 *     &lt;enumeration value="CUB"/&gt;
 *     &lt;enumeration value="CUW"/&gt;
 *     &lt;enumeration value="CXR"/&gt;
 *     &lt;enumeration value="CYM"/&gt;
 *     &lt;enumeration value="CYP"/&gt;
 *     &lt;enumeration value="CZE"/&gt;
 *     &lt;enumeration value="DEU"/&gt;
 *     &lt;enumeration value="DJI"/&gt;
 *     &lt;enumeration value="DMA"/&gt;
 *     &lt;enumeration value="DNK"/&gt;
 *     &lt;enumeration value="DOM"/&gt;
 *     &lt;enumeration value="DZA"/&gt;
 *     &lt;enumeration value="ECU"/&gt;
 *     &lt;enumeration value="EGY"/&gt;
 *     &lt;enumeration value="ERI"/&gt;
 *     &lt;enumeration value="ESH"/&gt;
 *     &lt;enumeration value="ESP"/&gt;
 *     &lt;enumeration value="EST"/&gt;
 *     &lt;enumeration value="ETH"/&gt;
 *     &lt;enumeration value="FIN"/&gt;
 *     &lt;enumeration value="FJI"/&gt;
 *     &lt;enumeration value="FLK"/&gt;
 *     &lt;enumeration value="FRA"/&gt;
 *     &lt;enumeration value="FRO"/&gt;
 *     &lt;enumeration value="FSM"/&gt;
 *     &lt;enumeration value="GAB"/&gt;
 *     &lt;enumeration value="GBR"/&gt;
 *     &lt;enumeration value="GEO"/&gt;
 *     &lt;enumeration value="GGY"/&gt;
 *     &lt;enumeration value="GHA"/&gt;
 *     &lt;enumeration value="GIB"/&gt;
 *     &lt;enumeration value="GIN"/&gt;
 *     &lt;enumeration value="GLP"/&gt;
 *     &lt;enumeration value="GMB"/&gt;
 *     &lt;enumeration value="GNB"/&gt;
 *     &lt;enumeration value="GNQ"/&gt;
 *     &lt;enumeration value="GRC"/&gt;
 *     &lt;enumeration value="GRD"/&gt;
 *     &lt;enumeration value="GRL"/&gt;
 *     &lt;enumeration value="GTM"/&gt;
 *     &lt;enumeration value="GUF"/&gt;
 *     &lt;enumeration value="GUM"/&gt;
 *     &lt;enumeration value="GUY"/&gt;
 *     &lt;enumeration value="HKG"/&gt;
 *     &lt;enumeration value="HMD"/&gt;
 *     &lt;enumeration value="HND"/&gt;
 *     &lt;enumeration value="HRV"/&gt;
 *     &lt;enumeration value="HTI"/&gt;
 *     &lt;enumeration value="HUN"/&gt;
 *     &lt;enumeration value="IDN"/&gt;
 *     &lt;enumeration value="IMN"/&gt;
 *     &lt;enumeration value="IND"/&gt;
 *     &lt;enumeration value="IOT"/&gt;
 *     &lt;enumeration value="IRL"/&gt;
 *     &lt;enumeration value="IRN"/&gt;
 *     &lt;enumeration value="IRQ"/&gt;
 *     &lt;enumeration value="ISL"/&gt;
 *     &lt;enumeration value="ISR"/&gt;
 *     &lt;enumeration value="ITA"/&gt;
 *     &lt;enumeration value="JAM"/&gt;
 *     &lt;enumeration value="JEY"/&gt;
 *     &lt;enumeration value="JOR"/&gt;
 *     &lt;enumeration value="JPN"/&gt;
 *     &lt;enumeration value="KAZ"/&gt;
 *     &lt;enumeration value="KEN"/&gt;
 *     &lt;enumeration value="KGZ"/&gt;
 *     &lt;enumeration value="KHM"/&gt;
 *     &lt;enumeration value="KIR"/&gt;
 *     &lt;enumeration value="KNA"/&gt;
 *     &lt;enumeration value="KOR"/&gt;
 *     &lt;enumeration value="KWT"/&gt;
 *     &lt;enumeration value="LAO"/&gt;
 *     &lt;enumeration value="LBN"/&gt;
 *     &lt;enumeration value="LBR"/&gt;
 *     &lt;enumeration value="LBY"/&gt;
 *     &lt;enumeration value="LCA"/&gt;
 *     &lt;enumeration value="LIE"/&gt;
 *     &lt;enumeration value="LKA"/&gt;
 *     &lt;enumeration value="LSO"/&gt;
 *     &lt;enumeration value="LTU"/&gt;
 *     &lt;enumeration value="LUX"/&gt;
 *     &lt;enumeration value="LVA"/&gt;
 *     &lt;enumeration value="MAC"/&gt;
 *     &lt;enumeration value="MAF"/&gt;
 *     &lt;enumeration value="MAR"/&gt;
 *     &lt;enumeration value="MCO"/&gt;
 *     &lt;enumeration value="MDA"/&gt;
 *     &lt;enumeration value="MDG"/&gt;
 *     &lt;enumeration value="MDV"/&gt;
 *     &lt;enumeration value="MEX"/&gt;
 *     &lt;enumeration value="MHL"/&gt;
 *     &lt;enumeration value="MKD"/&gt;
 *     &lt;enumeration value="MLI"/&gt;
 *     &lt;enumeration value="MLT"/&gt;
 *     &lt;enumeration value="MMR"/&gt;
 *     &lt;enumeration value="MNE"/&gt;
 *     &lt;enumeration value="MNG"/&gt;
 *     &lt;enumeration value="MNP"/&gt;
 *     &lt;enumeration value="MOZ"/&gt;
 *     &lt;enumeration value="MRT"/&gt;
 *     &lt;enumeration value="MSR"/&gt;
 *     &lt;enumeration value="MTQ"/&gt;
 *     &lt;enumeration value="MUS"/&gt;
 *     &lt;enumeration value="MWI"/&gt;
 *     &lt;enumeration value="MYS"/&gt;
 *     &lt;enumeration value="MYT"/&gt;
 *     &lt;enumeration value="NAM"/&gt;
 *     &lt;enumeration value="NCL"/&gt;
 *     &lt;enumeration value="NER"/&gt;
 *     &lt;enumeration value="NFK"/&gt;
 *     &lt;enumeration value="NGA"/&gt;
 *     &lt;enumeration value="NIC"/&gt;
 *     &lt;enumeration value="NIU"/&gt;
 *     &lt;enumeration value="NLD"/&gt;
 *     &lt;enumeration value="NOR"/&gt;
 *     &lt;enumeration value="NPL"/&gt;
 *     &lt;enumeration value="NRU"/&gt;
 *     &lt;enumeration value="NZL"/&gt;
 *     &lt;enumeration value="OMN"/&gt;
 *     &lt;enumeration value="PAK"/&gt;
 *     &lt;enumeration value="PAN"/&gt;
 *     &lt;enumeration value="PCN"/&gt;
 *     &lt;enumeration value="PER"/&gt;
 *     &lt;enumeration value="PHL"/&gt;
 *     &lt;enumeration value="PLW"/&gt;
 *     &lt;enumeration value="PNG"/&gt;
 *     &lt;enumeration value="POL"/&gt;
 *     &lt;enumeration value="PRI"/&gt;
 *     &lt;enumeration value="PRK"/&gt;
 *     &lt;enumeration value="PRT"/&gt;
 *     &lt;enumeration value="PRY"/&gt;
 *     &lt;enumeration value="PSE"/&gt;
 *     &lt;enumeration value="PYF"/&gt;
 *     &lt;enumeration value="QAT"/&gt;
 *     &lt;enumeration value="REU"/&gt;
 *     &lt;enumeration value="ROU"/&gt;
 *     &lt;enumeration value="RUS"/&gt;
 *     &lt;enumeration value="RWA"/&gt;
 *     &lt;enumeration value="SAU"/&gt;
 *     &lt;enumeration value="SDN"/&gt;
 *     &lt;enumeration value="SEN"/&gt;
 *     &lt;enumeration value="SGP"/&gt;
 *     &lt;enumeration value="SGS"/&gt;
 *     &lt;enumeration value="SHN"/&gt;
 *     &lt;enumeration value="SJM"/&gt;
 *     &lt;enumeration value="SLB"/&gt;
 *     &lt;enumeration value="SLE"/&gt;
 *     &lt;enumeration value="SLV"/&gt;
 *     &lt;enumeration value="SMR"/&gt;
 *     &lt;enumeration value="SOM"/&gt;
 *     &lt;enumeration value="SPM"/&gt;
 *     &lt;enumeration value="SRB"/&gt;
 *     &lt;enumeration value="SSD"/&gt;
 *     &lt;enumeration value="STP"/&gt;
 *     &lt;enumeration value="SUR"/&gt;
 *     &lt;enumeration value="SVK"/&gt;
 *     &lt;enumeration value="SVN"/&gt;
 *     &lt;enumeration value="SWE"/&gt;
 *     &lt;enumeration value="SWZ"/&gt;
 *     &lt;enumeration value="SXM"/&gt;
 *     &lt;enumeration value="SYC"/&gt;
 *     &lt;enumeration value="SYR"/&gt;
 *     &lt;enumeration value="TCA"/&gt;
 *     &lt;enumeration value="TCD"/&gt;
 *     &lt;enumeration value="TGO"/&gt;
 *     &lt;enumeration value="THA"/&gt;
 *     &lt;enumeration value="TJK"/&gt;
 *     &lt;enumeration value="TKL"/&gt;
 *     &lt;enumeration value="TKM"/&gt;
 *     &lt;enumeration value="TLS"/&gt;
 *     &lt;enumeration value="TON"/&gt;
 *     &lt;enumeration value="TTO"/&gt;
 *     &lt;enumeration value="TUN"/&gt;
 *     &lt;enumeration value="TUR"/&gt;
 *     &lt;enumeration value="TUV"/&gt;
 *     &lt;enumeration value="TWN"/&gt;
 *     &lt;enumeration value="TZA"/&gt;
 *     &lt;enumeration value="UGA"/&gt;
 *     &lt;enumeration value="UKR"/&gt;
 *     &lt;enumeration value="UMI"/&gt;
 *     &lt;enumeration value="URY"/&gt;
 *     &lt;enumeration value="USA"/&gt;
 *     &lt;enumeration value="UZB"/&gt;
 *     &lt;enumeration value="VAT"/&gt;
 *     &lt;enumeration value="VCT"/&gt;
 *     &lt;enumeration value="VEN"/&gt;
 *     &lt;enumeration value="VGB"/&gt;
 *     &lt;enumeration value="VIR"/&gt;
 *     &lt;enumeration value="VNM"/&gt;
 *     &lt;enumeration value="VUT"/&gt;
 *     &lt;enumeration value="WLF"/&gt;
 *     &lt;enumeration value="WSM"/&gt;
 *     &lt;enumeration value="YEM"/&gt;
 *     &lt;enumeration value="ZAF"/&gt;
 *     &lt;enumeration value="ZMB"/&gt;
 *     &lt;enumeration value="ZWE"/&gt;
 *     &lt;enumeration value="ZZZ"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "countryCodeEnumType")
@XmlEnum
public enum CountryCodeEnumType {


    /**
     * Aruba
     * 
     */
    ABW,

    /**
     * Afghanistan
     * 
     */
    AFG,

    /**
     * Angola
     * 
     */
    AGO,

    /**
     * Anguilla
     * 
     */
    AIA,

    /**
     * Åland Islands
     * 
     */
    ALA,

    /**
     * Albania
     * 
     */
    ALB,

    /**
     * Andorra
     * 
     */
    AND,

    /**
     * United Arab Emirates
     * 
     */
    ARE,

    /**
     * Argentina
     * 
     */
    ARG,

    /**
     * Armenia
     * 
     */
    ARM,

    /**
     * American Samoa
     * 
     */
    ASM,

    /**
     * Antarctica
     * 
     */
    ATA,

    /**
     * French Southern Territories
     * 
     */
    ATF,

    /**
     * Antigua and Barbuda
     * 
     */
    ATG,

    /**
     * Australia
     * 
     */
    AUS,

    /**
     * Austria
     * 
     */
    AUT,

    /**
     * Azerbaijan
     * 
     */
    AZE,

    /**
     * Burundi
     * 
     */
    BDI,

    /**
     * Belgium
     * 
     */
    BEL,

    /**
     * Benin
     * 
     */
    BEN,

    /**
     * Bonaire, Sint Eustatius and Saba
     *                     
     * 
     */
    BES,

    /**
     * Burkina Faso
     * 
     */
    BFA,

    /**
     * Bangladesh
     * 
     */
    BGD,

    /**
     * Bulgaria
     * 
     */
    BGR,

    /**
     * Bahrain
     * 
     */
    BHR,

    /**
     * Bahamas
     * 
     */
    BHS,

    /**
     * Bosnia and Herzegovina
     * 
     */
    BIH,

    /**
     * Saint Barthélemy
     * 
     */
    BLM,

    /**
     * Belarus
     * 
     */
    BLR,

    /**
     * Belize
     * 
     */
    BLZ,

    /**
     * Bermuda
     * 
     */
    BMU,

    /**
     * Bolivia, Plurinational State of
     *                     
     * 
     */
    BOL,

    /**
     * Brazil
     * 
     */
    BRA,

    /**
     * Barbados
     * 
     */
    BRB,

    /**
     * Brunei Darussalam
     * 
     */
    BRN,

    /**
     * Bhutan
     * 
     */
    BTN,

    /**
     * Bouvet Island
     * 
     */
    BVT,

    /**
     * Botswana
     * 
     */
    BWA,

    /**
     * Central African Republic
     * 
     */
    CAF,

    /**
     * Canada
     * 
     */
    CAN,

    /**
     * Cocos (Keeling) Islands
     * 
     */
    CCK,

    /**
     * Switzerland
     * 
     */
    CHE,

    /**
     * Chile
     * 
     */
    CHL,

    /**
     * China
     * 
     */
    CHN,

    /**
     * Côte d'Ivoire
     * 
     */
    CIV,

    /**
     * Cameroon
     * 
     */
    CMR,

    /**
     * Congo, the Democratic Republic of the
     * 
     */
    COD,

    /**
     * Congo
     * 
     */
    COG,

    /**
     * Cook Islands
     * 
     */
    COK,

    /**
     * Colombia
     * 
     */
    COL,

    /**
     * Comoros
     * 
     */
    COM,

    /**
     * Cape Verde
     * 
     */
    CPV,

    /**
     * Costa Rica
     * 
     */
    CRI,

    /**
     * Cuba
     * 
     */
    CUB,

    /**
     * Curaçao
     * 
     */
    CUW,

    /**
     * Christmas Island
     * 
     */
    CXR,

    /**
     * Cayman Islands
     * 
     */
    CYM,

    /**
     * Cyprus
     * 
     */
    CYP,

    /**
     * Czech Republic
     * 
     */
    CZE,

    /**
     * Germany
     * 
     */
    DEU,

    /**
     * Djibouti
     * 
     */
    DJI,

    /**
     * Dominica
     * 
     */
    DMA,

    /**
     * Denmark
     * 
     */
    DNK,

    /**
     * Dominican Republic
     * 
     */
    DOM,

    /**
     * Algeria
     * 
     */
    DZA,

    /**
     * Ecuador
     * 
     */
    ECU,

    /**
     * Egypt
     * 
     */
    EGY,

    /**
     * Eritrea
     * 
     */
    ERI,

    /**
     * Western Sahara
     * 
     */
    ESH,

    /**
     * Spain
     * 
     */
    ESP,

    /**
     * Estonia
     * 
     */
    EST,

    /**
     * Ethiopia
     * 
     */
    ETH,

    /**
     * Finland
     * 
     */
    FIN,

    /**
     * Fiji
     * 
     */
    FJI,

    /**
     * Falkland Islands (Malvinas)
     * 
     */
    FLK,

    /**
     * France
     * 
     */
    FRA,

    /**
     * Faroe Islands
     * 
     */
    FRO,

    /**
     * Micronesia, Federated States of
     * 
     */
    FSM,

    /**
     * Gabon
     * 
     */
    GAB,

    /**
     * United Kingdom
     * 
     */
    GBR,

    /**
     * Georgia
     * 
     */
    GEO,

    /**
     * Guernsey
     * 
     */
    GGY,

    /**
     * Ghana
     * 
     */
    GHA,

    /**
     * Gibraltar
     * 
     */
    GIB,

    /**
     * Guinea
     * 
     */
    GIN,

    /**
     * Guadeloupe
     * 
     */
    GLP,

    /**
     * Gambia
     * 
     */
    GMB,

    /**
     * Guinea-Bissau
     * 
     */
    GNB,

    /**
     * Equatorial Guinea
     * 
     */
    GNQ,

    /**
     * Greece
     * 
     */
    GRC,

    /**
     * Grenada
     * 
     */
    GRD,

    /**
     * Greenland
     * 
     */
    GRL,

    /**
     * Guatemala
     * 
     */
    GTM,

    /**
     * French Guiana
     * 
     */
    GUF,

    /**
     * Guam
     * 
     */
    GUM,

    /**
     * Guyana
     * 
     */
    GUY,

    /**
     * Hong Kong
     * 
     */
    HKG,

    /**
     * Heard Island and McDonald Islands
     * 
     */
    HMD,

    /**
     * Honduras
     * 
     */
    HND,

    /**
     * Croatia
     * 
     */
    HRV,

    /**
     * Haiti
     * 
     */
    HTI,

    /**
     * Hungary
     * 
     */
    HUN,

    /**
     * Indonesia
     * 
     */
    IDN,

    /**
     * Isle of Man
     * 
     */
    IMN,

    /**
     * India
     * 
     */
    IND,

    /**
     * British Indian Ocean Territory
     * 
     */
    IOT,

    /**
     * Ireland
     * 
     */
    IRL,

    /**
     * Iran, Islamic Republic of
     * 
     */
    IRN,

    /**
     * Iraq
     * 
     */
    IRQ,

    /**
     * Iceland
     * 
     */
    ISL,

    /**
     * Israel
     * 
     */
    ISR,

    /**
     * Italy
     * 
     */
    ITA,

    /**
     * Jamaica
     * 
     */
    JAM,

    /**
     * Jersey
     * 
     */
    JEY,

    /**
     * Jordan
     * 
     */
    JOR,

    /**
     * Japan
     * 
     */
    JPN,

    /**
     * Kazakhstan
     * 
     */
    KAZ,

    /**
     * Kenya
     * 
     */
    KEN,

    /**
     * Kyrgyzstan
     * 
     */
    KGZ,

    /**
     * Cambodia
     * 
     */
    KHM,

    /**
     * Kiribati
     * 
     */
    KIR,

    /**
     * Saint Kitts and Nevis
     * 
     */
    KNA,

    /**
     * Korea, Republic of
     * 
     */
    KOR,

    /**
     * Kuwait
     * 
     */
    KWT,

    /**
     * Lao People's Democratic Republic
     *                     
     * 
     */
    LAO,

    /**
     * Lebanon
     * 
     */
    LBN,

    /**
     * Liberia
     * 
     */
    LBR,

    /**
     * Libya
     * 
     */
    LBY,

    /**
     * Saint Lucia
     * 
     */
    LCA,

    /**
     * Liechtenstein
     * 
     */
    LIE,

    /**
     * Sri Lanka
     * 
     */
    LKA,

    /**
     * Lesotho
     * 
     */
    LSO,

    /**
     * Lithuania
     * 
     */
    LTU,

    /**
     * Luxembourg
     * 
     */
    LUX,

    /**
     * Latvia
     * 
     */
    LVA,

    /**
     * Macao
     * 
     */
    MAC,

    /**
     * Saint Martin (French part)
     * 
     */
    MAF,

    /**
     * Morocco
     * 
     */
    MAR,

    /**
     * Monaco
     * 
     */
    MCO,

    /**
     * Moldova, Republic of
     * 
     */
    MDA,

    /**
     * Madagascar
     * 
     */
    MDG,

    /**
     * Maldives
     * 
     */
    MDV,

    /**
     * Mexico
     * 
     */
    MEX,

    /**
     * Marshall Islands
     * 
     */
    MHL,

    /**
     * Macedonia, the former Yugoslav Republic of
     * 
     */
    MKD,

    /**
     * Mali
     * 
     */
    MLI,

    /**
     * Malta
     * 
     */
    MLT,

    /**
     * Myanmar
     * 
     */
    MMR,

    /**
     * Montenegro
     * 
     */
    MNE,

    /**
     * Mongolia
     * 
     */
    MNG,

    /**
     * Northern Mariana Islands
     * 
     */
    MNP,

    /**
     * Mozambique
     * 
     */
    MOZ,

    /**
     * Mauritania
     * 
     */
    MRT,

    /**
     * Montserrat
     * 
     */
    MSR,

    /**
     * Martinique
     * 
     */
    MTQ,

    /**
     * Mauritius
     * 
     */
    MUS,

    /**
     * Malawi
     * 
     */
    MWI,

    /**
     * Malaysia
     * 
     */
    MYS,

    /**
     * Mayotte
     * 
     */
    MYT,

    /**
     * Namibia
     * 
     */
    NAM,

    /**
     * New Caledonia
     * 
     */
    NCL,

    /**
     * Niger
     * 
     */
    NER,

    /**
     * Norfolk Island
     * 
     */
    NFK,

    /**
     * Nigeria
     * 
     */
    NGA,

    /**
     * Nicaragua
     * 
     */
    NIC,

    /**
     * Niue
     * 
     */
    NIU,

    /**
     * Netherlands
     * 
     */
    NLD,

    /**
     * Norway
     * 
     */
    NOR,

    /**
     * Nepal
     * 
     */
    NPL,

    /**
     * Nauru
     * 
     */
    NRU,

    /**
     * New Zealand
     * 
     */
    NZL,

    /**
     * Oman
     * 
     */
    OMN,

    /**
     * Pakistan
     * 
     */
    PAK,

    /**
     * Panama
     * 
     */
    PAN,

    /**
     * Pitcairn
     * 
     */
    PCN,

    /**
     * Peru
     * 
     */
    PER,

    /**
     * Philippines
     * 
     */
    PHL,

    /**
     * Palau
     * 
     */
    PLW,

    /**
     * Papua New Guinea
     * 
     */
    PNG,

    /**
     * Poland
     * 
     */
    POL,

    /**
     * Puerto Rico
     * 
     */
    PRI,

    /**
     * Korea, Democratic People's Republic of
     * 
     */
    PRK,

    /**
     * Portugal
     * 
     */
    PRT,

    /**
     * Paraguay
     * 
     */
    PRY,

    /**
     * Palestine, State of
     * 
     */
    PSE,

    /**
     * French Polynesia
     * 
     */
    PYF,

    /**
     * Qatar
     * 
     */
    QAT,

    /**
     * Réunion
     * 
     */
    REU,

    /**
     * Romania
     * 
     */
    ROU,

    /**
     * Russian Federation
     * 
     */
    RUS,

    /**
     * Rwanda
     * 
     */
    RWA,

    /**
     * Saudi Arabia
     * 
     */
    SAU,

    /**
     * Sudan
     * 
     */
    SDN,

    /**
     * Senegal
     * 
     */
    SEN,

    /**
     * Singapore
     * 
     */
    SGP,

    /**
     * South Georgia and the South Sandwich Islands
     * 
     */
    SGS,

    /**
     * Saint Helena, Ascension and Tristan da Cunha
     * 
     */
    SHN,

    /**
     * Svalbard and Jan Mayen
     * 
     */
    SJM,

    /**
     * Solomon Islands
     * 
     */
    SLB,

    /**
     * Sierra Leone
     * 
     */
    SLE,

    /**
     * El Salvador
     * 
     */
    SLV,

    /**
     * San Marino
     * 
     */
    SMR,

    /**
     * Somalia
     * 
     */
    SOM,

    /**
     * Saint Pierre and Miquelon
     * 
     */
    SPM,

    /**
     * Serbia
     * 
     */
    SRB,

    /**
     * South Sudan
     * 
     */
    SSD,

    /**
     * Sao Tome and Principe
     * 
     */
    STP,

    /**
     * Suriname
     * 
     */
    SUR,

    /**
     * Slovakia
     * 
     */
    SVK,

    /**
     * Slovenia
     * 
     */
    SVN,

    /**
     * Sweden
     * 
     */
    SWE,

    /**
     * Swaziland
     * 
     */
    SWZ,

    /**
     * Sint Maarten (Dutch part)
     * 
     */
    SXM,

    /**
     * Seychelles
     * 
     */
    SYC,

    /**
     * Syrian Arab Republic
     * 
     */
    SYR,

    /**
     * Turks and Caicos Islands
     * 
     */
    TCA,

    /**
     * Chad
     * 
     */
    TCD,

    /**
     * Togo
     * 
     */
    TGO,

    /**
     * Thailand
     * 
     */
    THA,

    /**
     * Tajikistan
     * 
     */
    TJK,

    /**
     * Tokelau
     * 
     */
    TKL,

    /**
     * Turkmenistan
     * 
     */
    TKM,

    /**
     * Timor-Leste
     * 
     */
    TLS,

    /**
     * Tonga
     * 
     */
    TON,

    /**
     * Trinidad and Tobago
     * 
     */
    TTO,

    /**
     * Tunisia
     * 
     */
    TUN,

    /**
     * Turkey
     * 
     */
    TUR,

    /**
     * Tuvalu
     * 
     */
    TUV,

    /**
     * Taiwan, Province of China
     * 
     */
    TWN,

    /**
     * Tanzania, United Republic of
     * 
     */
    TZA,

    /**
     * Uganda
     * 
     */
    UGA,

    /**
     * Ukraine
     * 
     */
    UKR,

    /**
     * United States Minor Outlying Islands
     * 
     */
    UMI,

    /**
     * Uruguay
     * 
     */
    URY,

    /**
     * United States
     * 
     */
    USA,

    /**
     * Uzbekistan
     * 
     */
    UZB,

    /**
     * Holy See (Vatican City State)
     * 
     */
    VAT,

    /**
     * Saint Vincent and the Grenadines
     * 
     */
    VCT,

    /**
     * Venezuela, Bolivarian Republic of
     * 
     */
    VEN,

    /**
     * Virgin Islands, British
     * 
     */
    VGB,

    /**
     * Virgin Islands, U.S.
     * 
     */
    VIR,

    /**
     * Viet Nam
     * 
     */
    VNM,

    /**
     * Vanuatu
     * 
     */
    VUT,

    /**
     * Wallis and Futuna
     * 
     */
    WLF,

    /**
     * Samoa
     * 
     */
    WSM,

    /**
     * Yemen
     * 
     */
    YEM,

    /**
     * South Africa
     * 
     */
    ZAF,

    /**
     * Zambia
     * 
     */
    ZMB,

    /**
     * Zimbabwe
     * 
     */
    ZWE,

    /**
     * Unknown
     * 
     */
    ZZZ;

    public String value() {
        return name();
    }

    public static CountryCodeEnumType fromValue(String v) {
        return valueOf(v);
    }

}
