//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 04:23:17 PM IST 
//


package ConsumerFinancing.equifax.models.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for identityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="identityType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="bureau-reference" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}BureauReferenceSimpleType" minOccurs="0"/&gt;
 *         &lt;element name="individual-name" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}individual-nameType"&gt;
 *                 &lt;attGroup ref="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}reported-datesGroup"/&gt;
 *                 &lt;attribute name="last-credit-enquiry-date" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="gender" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd&gt;genderType"&gt;
 *                 &lt;attribute name="code" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}gender-codeType" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="date-of-birth" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;date"&gt;
 *                 &lt;attGroup ref="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}reported-datesGroup"/&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="drivers-licence" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}photoid-cardType"&gt;
 *                 &lt;attGroup ref="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}reported-datesGroup"/&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="lodged-complaint" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;boolean"&gt;
 *                 &lt;attribute name="reported-date" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}ReportedDateSimpleType" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="is-deceased" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;boolean"&gt;
 *                 &lt;attribute name="reported-date" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}ReportedDateSimpleType" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="do-not-provide-credit" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;simpleContent&gt;
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;boolean"&gt;
 *                 &lt;attribute name="reported-date" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}ReportedDateSimpleType" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/simpleContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="other-indicators" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="indicator" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;extension base="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}key-value-pairType"&gt;
 *                           &lt;attribute name="reported-date" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}ReportedDateSimpleType" /&gt;
 *                         &lt;/extension&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}disputeGroup"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "identityType", propOrder = {
    "bureauReference",
    "individualName",
    "gender",
    "dateOfBirth",
    "driversLicence",
    "lodgedComplaint",
    "isDeceased",
    "doNotProvideCredit",
    "otherIndicators"
})
@XmlSeeAlso({
    ConsumerFinancing.equifax.models.model.EnquiryReportType.PrimaryMatch.class,
    ConsumerFinancing.equifax.models.model.EnquiryReportType.OtherIdentities.OtherIdentity.class
})
public class IdentityType {

    @XmlElement(name = "bureau-reference")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String bureauReference;
    @XmlElement(name = "individual-name")
    protected IdentityType.IndividualName individualName;
    protected IdentityType.Gender gender;
    @XmlElement(name = "date-of-birth")
    protected IdentityType.DateOfBirth dateOfBirth;
    @XmlElement(name = "drivers-licence")
    protected IdentityType.DriversLicence driversLicence;
    @XmlElement(name = "lodged-complaint")
    protected IdentityType.LodgedComplaint lodgedComplaint;
    @XmlElement(name = "is-deceased")
    protected IdentityType.IsDeceased isDeceased;
    @XmlElement(name = "do-not-provide-credit")
    protected IdentityType.DoNotProvideCredit doNotProvideCredit;
    @XmlElement(name = "other-indicators")
    protected IdentityType.OtherIndicators otherIndicators;
    @XmlAttribute(name = "is-disputed")
    protected Boolean isDisputed;
    @XmlAttribute(name = "dispute-reported-date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar disputeReportedDate;
    @XmlAttribute(name = "dispute-code")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String disputeCode;

    /**
     * Gets the value of the bureauReference property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBureauReference() {
        return bureauReference;
    }

    /**
     * Sets the value of the bureauReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBureauReference(String value) {
        this.bureauReference = value;
    }

    /**
     * Gets the value of the individualName property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityType.IndividualName }
     *     
     */
    public IdentityType.IndividualName getIndividualName() {
        return individualName;
    }

    /**
     * Sets the value of the individualName property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityType.IndividualName }
     *     
     */
    public void setIndividualName(IdentityType.IndividualName value) {
        this.individualName = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityType.Gender }
     *     
     */
    public IdentityType.Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityType.Gender }
     *     
     */
    public void setGender(IdentityType.Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityType.DateOfBirth }
     *     
     */
    public IdentityType.DateOfBirth getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityType.DateOfBirth }
     *     
     */
    public void setDateOfBirth(IdentityType.DateOfBirth value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the driversLicence property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityType.DriversLicence }
     *     
     */
    public IdentityType.DriversLicence getDriversLicence() {
        return driversLicence;
    }

    /**
     * Sets the value of the driversLicence property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityType.DriversLicence }
     *     
     */
    public void setDriversLicence(IdentityType.DriversLicence value) {
        this.driversLicence = value;
    }

    /**
     * Gets the value of the lodgedComplaint property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityType.LodgedComplaint }
     *     
     */
    public IdentityType.LodgedComplaint getLodgedComplaint() {
        return lodgedComplaint;
    }

    /**
     * Sets the value of the lodgedComplaint property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityType.LodgedComplaint }
     *     
     */
    public void setLodgedComplaint(IdentityType.LodgedComplaint value) {
        this.lodgedComplaint = value;
    }

    /**
     * Gets the value of the isDeceased property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityType.IsDeceased }
     *     
     */
    public IdentityType.IsDeceased getIsDeceased() {
        return isDeceased;
    }

    /**
     * Sets the value of the isDeceased property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityType.IsDeceased }
     *     
     */
    public void setIsDeceased(IdentityType.IsDeceased value) {
        this.isDeceased = value;
    }

    /**
     * Gets the value of the doNotProvideCredit property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityType.DoNotProvideCredit }
     *     
     */
    public IdentityType.DoNotProvideCredit getDoNotProvideCredit() {
        return doNotProvideCredit;
    }

    /**
     * Sets the value of the doNotProvideCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityType.DoNotProvideCredit }
     *     
     */
    public void setDoNotProvideCredit(IdentityType.DoNotProvideCredit value) {
        this.doNotProvideCredit = value;
    }

    /**
     * Gets the value of the otherIndicators property.
     * 
     * @return
     *     possible object is
     *     {@link IdentityType.OtherIndicators }
     *     
     */
    public IdentityType.OtherIndicators getOtherIndicators() {
        return otherIndicators;
    }

    /**
     * Sets the value of the otherIndicators property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentityType.OtherIndicators }
     *     
     */
    public void setOtherIndicators(IdentityType.OtherIndicators value) {
        this.otherIndicators = value;
    }

    /**
     * Gets the value of the isDisputed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDisputed() {
        return isDisputed;
    }

    /**
     * Sets the value of the isDisputed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDisputed(Boolean value) {
        this.isDisputed = value;
    }

    /**
     * Gets the value of the disputeReportedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDisputeReportedDate() {
        return disputeReportedDate;
    }

    /**
     * Sets the value of the disputeReportedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDisputeReportedDate(XMLGregorianCalendar value) {
        this.disputeReportedDate = value;
    }

    /**
     * Gets the value of the disputeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisputeCode() {
        return disputeCode;
    }

    /**
     * Sets the value of the disputeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisputeCode(String value) {
        this.disputeCode = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;date"&gt;
     *       &lt;attGroup ref="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}reported-datesGroup"/&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DateOfBirth {

        @XmlValue
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar value;
        @XmlAttribute(name = "first-reported-date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar firstReportedDate;
        @XmlAttribute(name = "last-reported-date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar lastReportedDate;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setValue(XMLGregorianCalendar value) {
            this.value = value;
        }

        /**
         * Gets the value of the firstReportedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFirstReportedDate() {
            return firstReportedDate;
        }

        /**
         * Sets the value of the firstReportedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFirstReportedDate(XMLGregorianCalendar value) {
            this.firstReportedDate = value;
        }

        /**
         * Gets the value of the lastReportedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getLastReportedDate() {
            return lastReportedDate;
        }

        /**
         * Sets the value of the lastReportedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setLastReportedDate(XMLGregorianCalendar value) {
            this.lastReportedDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;boolean"&gt;
     *       &lt;attribute name="reported-date" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}ReportedDateSimpleType" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class DoNotProvideCredit {

        @XmlValue
        protected boolean value;
        @XmlAttribute(name = "reported-date")
        protected XMLGregorianCalendar reportedDate;

        /**
         * Gets the value of the value property.
         * 
         */
        public boolean isValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(boolean value) {
            this.value = value;
        }

        /**
         * Gets the value of the reportedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getReportedDate() {
            return reportedDate;
        }

        /**
         * Sets the value of the reportedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setReportedDate(XMLGregorianCalendar value) {
            this.reportedDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}photoid-cardType"&gt;
     *       &lt;attGroup ref="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}reported-datesGroup"/&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class DriversLicence
        extends PhotoidCardType
    {

        @XmlAttribute(name = "first-reported-date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar firstReportedDate;
        @XmlAttribute(name = "last-reported-date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar lastReportedDate;

        /**
         * Gets the value of the firstReportedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFirstReportedDate() {
            return firstReportedDate;
        }

        /**
         * Sets the value of the firstReportedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFirstReportedDate(XMLGregorianCalendar value) {
            this.firstReportedDate = value;
        }

        /**
         * Gets the value of the lastReportedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getLastReportedDate() {
            return lastReportedDate;
        }

        /**
         * Sets the value of the lastReportedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setLastReportedDate(XMLGregorianCalendar value) {
            this.lastReportedDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd&gt;genderType"&gt;
     *       &lt;attribute name="code" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}gender-codeType" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Gender {

        @XmlValue
        protected GenderType value;
        @XmlAttribute(name = "code")
        protected GenderCodeType code;

        /**
         * Enumerated simpleType for an individual's gender
         * 
         * @return
         *     possible object is
         *     {@link GenderType }
         *     
         */
        public GenderType getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link GenderType }
         *     
         */
        public void setValue(GenderType value) {
            this.value = value;
        }

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link GenderCodeType }
         *     
         */
        public GenderCodeType getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link GenderCodeType }
         *     
         */
        public void setCode(GenderCodeType value) {
            this.code = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}individual-nameType"&gt;
     *       &lt;attGroup ref="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}reported-datesGroup"/&gt;
     *       &lt;attribute name="last-credit-enquiry-date" type="{http://www.w3.org/2001/XMLSchema}date" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class IndividualName
        extends IndividualNameType
    {

        @XmlAttribute(name = "last-credit-enquiry-date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar lastCreditEnquiryDate;
        @XmlAttribute(name = "first-reported-date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar firstReportedDate;
        @XmlAttribute(name = "last-reported-date")
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar lastReportedDate;

        /**
         * Gets the value of the lastCreditEnquiryDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getLastCreditEnquiryDate() {
            return lastCreditEnquiryDate;
        }

        /**
         * Sets the value of the lastCreditEnquiryDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setLastCreditEnquiryDate(XMLGregorianCalendar value) {
            this.lastCreditEnquiryDate = value;
        }

        /**
         * Gets the value of the firstReportedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFirstReportedDate() {
            return firstReportedDate;
        }

        /**
         * Sets the value of the firstReportedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFirstReportedDate(XMLGregorianCalendar value) {
            this.firstReportedDate = value;
        }

        /**
         * Gets the value of the lastReportedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getLastReportedDate() {
            return lastReportedDate;
        }

        /**
         * Sets the value of the lastReportedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setLastReportedDate(XMLGregorianCalendar value) {
            this.lastReportedDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;boolean"&gt;
     *       &lt;attribute name="reported-date" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}ReportedDateSimpleType" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class IsDeceased {

        @XmlValue
        protected boolean value;
        @XmlAttribute(name = "reported-date")
        protected XMLGregorianCalendar reportedDate;

        /**
         * Gets the value of the value property.
         * 
         */
        public boolean isValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(boolean value) {
            this.value = value;
        }

        /**
         * Gets the value of the reportedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getReportedDate() {
            return reportedDate;
        }

        /**
         * Sets the value of the reportedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setReportedDate(XMLGregorianCalendar value) {
            this.reportedDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;simpleContent&gt;
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema&gt;boolean"&gt;
     *       &lt;attribute name="reported-date" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}ReportedDateSimpleType" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/simpleContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class LodgedComplaint {

        @XmlValue
        protected boolean value;
        @XmlAttribute(name = "reported-date")
        protected XMLGregorianCalendar reportedDate;

        /**
         * Gets the value of the value property.
         * 
         */
        public boolean isValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(boolean value) {
            this.value = value;
        }

        /**
         * Gets the value of the reportedDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getReportedDate() {
            return reportedDate;
        }

        /**
         * Sets the value of the reportedDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setReportedDate(XMLGregorianCalendar value) {
            this.reportedDate = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="indicator" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;extension base="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}key-value-pairType"&gt;
     *                 &lt;attribute name="reported-date" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}ReportedDateSimpleType" /&gt;
     *               &lt;/extension&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "indicator"
    })
    public static class OtherIndicators {

        @XmlElement(required = true)
        protected List<IdentityType.OtherIndicators.Indicator> indicator;

        /**
         * Gets the value of the indicator property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the indicator property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIndicator().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IdentityType.OtherIndicators.Indicator }
         * 
         * 
         */
        public List<IdentityType.OtherIndicators.Indicator> getIndicator() {
            if (indicator == null) {
                indicator = new ArrayList<IdentityType.OtherIndicators.Indicator>();
            }
            return this.indicator;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;extension base="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}key-value-pairType"&gt;
         *       &lt;attribute name="reported-date" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}ReportedDateSimpleType" /&gt;
         *     &lt;/extension&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class Indicator
            extends KeyValuePairType
        {

            @XmlAttribute(name = "reported-date")
            protected XMLGregorianCalendar reportedDate;

            /**
             * Gets the value of the reportedDate property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getReportedDate() {
                return reportedDate;
            }

            /**
             * Sets the value of the reportedDate property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setReportedDate(XMLGregorianCalendar value) {
                this.reportedDate = value;
            }

        }

    }

}
