//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 04:23:17 PM IST 
//


package ConsumerFinancing.equifax.models.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ConsumerFinancing.equifax.models.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Request_QNAME = new QName("http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd", "request");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ConsumerFinancing.equifax.models.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseType }
     * 
     */
    public ResponseType createResponseType() {
        return new ResponseType();
    }

    /**
     * Create an instance of {@link TicketResponseType }
     * 
     */
    public TicketResponseType createTicketResponseType() {
        return new TicketResponseType();
    }

    /**
     * Create an instance of {@link ScoreType }
     * 
     */
    public ScoreType createScoreType() {
        return new ScoreType();
    }

    /**
     * Create an instance of {@link OrganisationType }
     * 
     */
    public OrganisationType createOrganisationType() {
        return new OrganisationType();
    }

    /**
     * Create an instance of {@link PublicRecordOrConsumerCreditInformationType }
     * 
     */
    public PublicRecordOrConsumerCreditInformationType createPublicRecordOrConsumerCreditInformationType() {
        return new PublicRecordOrConsumerCreditInformationType();
    }

    /**
     * Create an instance of {@link PossibleMatchesType }
     * 
     */
    public PossibleMatchesType createPossibleMatchesType() {
        return new PossibleMatchesType();
    }

    /**
     * Create an instance of {@link PossibleMatchType }
     * 
     */
    public PossibleMatchType createPossibleMatchType() {
        return new PossibleMatchType();
    }

    /**
     * Create an instance of {@link PersonalInsolvencyType }
     * 
     */
    public PersonalInsolvencyType createPersonalInsolvencyType() {
        return new PersonalInsolvencyType();
    }

    /**
     * Create an instance of {@link IndividualInputEchoType }
     * 
     */
    public IndividualInputEchoType createIndividualInputEchoType() {
        return new IndividualInputEchoType();
    }

    /**
     * Create an instance of {@link IndividualInputStrictType }
     * 
     */
    public IndividualInputStrictType createIndividualInputStrictType() {
        return new IndividualInputStrictType();
    }

    /**
     * Create an instance of {@link IndividualInputType }
     * 
     */
    public IndividualInputType createIndividualInputType() {
        return new IndividualInputType();
    }

    /**
     * Create an instance of {@link IdentityType }
     * 
     */
    public IdentityType createIdentityType() {
        return new IdentityType();
    }

    /**
     * Create an instance of {@link IdentityType.OtherIndicators }
     * 
     */
    public IdentityType.OtherIndicators createIdentityTypeOtherIndicators() {
        return new IdentityType.OtherIndicators();
    }

    /**
     * Create an instance of {@link KeyValuePairType }
     * 
     */
    public KeyValuePairType createKeyValuePairType() {
        return new KeyValuePairType();
    }

    /**
     * Create an instance of {@link EventType }
     * 
     */
    public EventType createEventType() {
        return new EventType();
    }

    /**
     * Create an instance of {@link EventType.EventDetails }
     * 
     */
    public EventType.EventDetails createEventTypeEventDetails() {
        return new EventType.EventDetails();
    }

    /**
     * Create an instance of {@link EventType.EventDetails.Property }
     * 
     */
    public EventType.EventDetails.Property createEventTypeEventDetailsProperty() {
        return new EventType.EventDetails.Property();
    }

    /**
     * Create an instance of {@link EnquiryReportType }
     * 
     */
    public EnquiryReportType createEnquiryReportType() {
        return new EnquiryReportType();
    }

    /**
     * Create an instance of {@link EnquiryReportType.OtherIdentities }
     * 
     */
    public EnquiryReportType.OtherIdentities createEnquiryReportTypeOtherIdentities() {
        return new EnquiryReportType.OtherIdentities();
    }

    /**
     * Create an instance of {@link EnquiryType }
     * 
     */
    public EnquiryType createEnquiryType() {
        return new EnquiryType();
    }

    /**
     * Create an instance of {@link CommercialDefaultRecordType }
     * 
     */
    public CommercialDefaultRecordType createCommercialDefaultRecordType() {
        return new CommercialDefaultRecordType();
    }

    /**
     * Create an instance of {@link CommercialDefaultType }
     * 
     */
    public CommercialDefaultType createCommercialDefaultType() {
        return new CommercialDefaultType();
    }

    /**
     * Create an instance of {@link ConsumerDefaultType }
     * 
     */
    public ConsumerDefaultType createConsumerDefaultType() {
        return new ConsumerDefaultType();
    }

    /**
     * Create an instance of {@link CreditEnquiryType }
     * 
     */
    public CreditEnquiryType createCreditEnquiryType() {
        return new CreditEnquiryType();
    }

    /**
     * Create an instance of {@link CourtActionType }
     * 
     */
    public CourtActionType createCourtActionType() {
        return new CourtActionType();
    }

    /**
     * Create an instance of {@link CommercialCreditAccountType }
     * 
     */
    public CommercialCreditAccountType createCommercialCreditAccountType() {
        return new CommercialCreditAccountType();
    }

    /**
     * Create an instance of {@link CommercialCreditAccountType.LatestCreditProvider }
     * 
     */
    public CommercialCreditAccountType.LatestCreditProvider createCommercialCreditAccountTypeLatestCreditProvider() {
        return new CommercialCreditAccountType.LatestCreditProvider();
    }

    /**
     * Create an instance of {@link ConsumerCreditAccountType }
     * 
     */
    public ConsumerCreditAccountType createConsumerCreditAccountType() {
        return new ConsumerCreditAccountType();
    }

    /**
     * Create an instance of {@link ConsumerCreditAccountType.LatestCreditProvider }
     * 
     */
    public ConsumerCreditAccountType.LatestCreditProvider createConsumerCreditAccountTypeLatestCreditProvider() {
        return new ConsumerCreditAccountType.LatestCreditProvider();
    }

    /**
     * Create an instance of {@link ContributingFactorType }
     * 
     */
    public ContributingFactorType createContributingFactorType() {
        return new ContributingFactorType();
    }

    /**
     * Create an instance of {@link ConsumerCreditFileType }
     * 
     */
    public ConsumerCreditFileType createConsumerCreditFileType() {
        return new ConsumerCreditFileType();
    }

    /**
     * Create an instance of {@link CommercialCreditFileType }
     * 
     */
    public CommercialCreditFileType createCommercialCreditFileType() {
        return new CommercialCreditFileType();
    }

    /**
     * Create an instance of {@link CharacteristicType }
     * 
     */
    public CharacteristicType createCharacteristicType() {
        return new CharacteristicType();
    }

    /**
     * Create an instance of {@link BusinessNameType }
     * 
     */
    public BusinessNameType createBusinessNameType() {
        return new BusinessNameType();
    }

    /**
     * Create an instance of {@link TicketResponseType.GeneralMessages }
     * 
     */
    public TicketResponseType.GeneralMessages createTicketResponseTypeGeneralMessages() {
        return new TicketResponseType.GeneralMessages();
    }

    /**
     * Create an instance of {@link MessagesType }
     * 
     */
    public MessagesType createMessagesType() {
        return new MessagesType();
    }

    /**
     * Create an instance of {@link ResponseType.ProductData }
     * 
     */
    public ResponseType.ProductData createResponseTypeProductData() {
        return new ResponseType.ProductData();
    }

    /**
     * Create an instance of {@link ProductHeaderType }
     * 
     */
    public ProductHeaderType createProductHeaderType() {
        return new ProductHeaderType();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link RequestType.EnquiryHeader }
     * 
     */
    public RequestType.EnquiryHeader createRequestTypeEnquiryHeader() {
        return new RequestType.EnquiryHeader();
    }

    /**
     * Create an instance of {@link RequestByEnquiryId }
     * 
     */
    public RequestByEnquiryId createRequestByEnquiryId() {
        return new RequestByEnquiryId();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link ResponseType.Errors }
     * 
     */
    public ResponseType.Errors createResponseTypeErrors() {
        return new ResponseType.Errors();
    }

    /**
     * Create an instance of {@link TicketResponse }
     * 
     */
    public TicketResponse createTicketResponse() {
        return new TicketResponse();
    }

    /**
     * Create an instance of {@link TicketResponseType.Errors }
     * 
     */
    public TicketResponseType.Errors createTicketResponseTypeErrors() {
        return new TicketResponseType.Errors();
    }

    /**
     * Create an instance of {@link AdditionalDataFieldsType }
     * 
     */
    public AdditionalDataFieldsType createAdditionalDataFieldsType() {
        return new AdditionalDataFieldsType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link AddressInputType }
     * 
     */
    public AddressInputType createAddressInputType() {
        return new AddressInputType();
    }

    /**
     * Create an instance of {@link AdministrationIdType }
     * 
     */
    public AdministrationIdType createAdministrationIdType() {
        return new AdministrationIdType();
    }

    /**
     * Create an instance of {@link AssociationInformationType }
     * 
     */
    public AssociationInformationType createAssociationInformationType() {
        return new AssociationInformationType();
    }

    /**
     * Create an instance of {@link BusinessRegistrationType }
     * 
     */
    public BusinessRegistrationType createBusinessRegistrationType() {
        return new BusinessRegistrationType();
    }

    /**
     * Create an instance of {@link OrganisationSummaryType }
     * 
     */
    public OrganisationSummaryType createOrganisationSummaryType() {
        return new OrganisationSummaryType();
    }

    /**
     * Create an instance of {@link CountryType }
     * 
     */
    public CountryType createCountryType() {
        return new CountryType();
    }

    /**
     * Create an instance of {@link CreditProviderType }
     * 
     */
    public CreditProviderType createCreditProviderType() {
        return new CreditProviderType();
    }

    /**
     * Create an instance of {@link DataBlockType }
     * 
     */
    public DataBlockType createDataBlockType() {
        return new DataBlockType();
    }

    /**
     * Create an instance of {@link DataLevelType }
     * 
     */
    public DataLevelType createDataLevelType() {
        return new DataLevelType();
    }

    /**
     * Create an instance of {@link ConsumerDefaultRecordType }
     * 
     */
    public ConsumerDefaultRecordType createConsumerDefaultRecordType() {
        return new ConsumerDefaultRecordType();
    }

    /**
     * Create an instance of {@link DirectorshipType }
     * 
     */
    public DirectorshipType createDirectorshipType() {
        return new DirectorshipType();
    }

    /**
     * Create an instance of {@link DisqualifiedDirectorshipType }
     * 
     */
    public DisqualifiedDirectorshipType createDisqualifiedDirectorshipType() {
        return new DisqualifiedDirectorshipType();
    }

    /**
     * Create an instance of {@link EmployerType }
     * 
     */
    public EmployerType createEmployerType() {
        return new EmployerType();
    }

    /**
     * Create an instance of {@link EmployerInputType }
     * 
     */
    public EmployerInputType createEmployerInputType() {
        return new EmployerInputType();
    }

    /**
     * Create an instance of {@link ErrorType }
     * 
     */
    public ErrorType createErrorType() {
        return new ErrorType();
    }

    /**
     * Create an instance of {@link FileBanReportType }
     * 
     */
    public FileBanReportType createFileBanReportType() {
        return new FileBanReportType();
    }

    /**
     * Create an instance of {@link FileNoteType }
     * 
     */
    public FileNoteType createFileNoteType() {
        return new FileNoteType();
    }

    /**
     * Create an instance of {@link IdReferencesType }
     * 
     */
    public IdReferencesType createIdReferencesType() {
        return new IdReferencesType();
    }

    /**
     * Create an instance of {@link IndividualNameInputType }
     * 
     */
    public IndividualNameInputType createIndividualNameInputType() {
        return new IndividualNameInputType();
    }

    /**
     * Create an instance of {@link IndividualNameType }
     * 
     */
    public IndividualNameType createIndividualNameType() {
        return new IndividualNameType();
    }

    /**
     * Create an instance of {@link MoneyType }
     * 
     */
    public MoneyType createMoneyType() {
        return new MoneyType();
    }

    /**
     * Create an instance of {@link PaymentType }
     * 
     */
    public PaymentType createPaymentType() {
        return new PaymentType();
    }

    /**
     * Create an instance of {@link PhotoidCardType }
     * 
     */
    public PhotoidCardType createPhotoidCardType() {
        return new PhotoidCardType();
    }

    /**
     * Create an instance of {@link RequestByEnquiryIdType }
     * 
     */
    public RequestByEnquiryIdType createRequestByEnquiryIdType() {
        return new RequestByEnquiryIdType();
    }

    /**
     * Create an instance of {@link StateType }
     * 
     */
    public StateType createStateType() {
        return new StateType();
    }

    /**
     * Create an instance of {@link SoleTraderRegistrationType }
     * 
     */
    public SoleTraderRegistrationType createSoleTraderRegistrationType() {
        return new SoleTraderRegistrationType();
    }

    /**
     * Create an instance of {@link ScorecardType }
     * 
     */
    public ScorecardType createScorecardType() {
        return new ScorecardType();
    }

    /**
     * Create an instance of {@link TrusteeType }
     * 
     */
    public TrusteeType createTrusteeType() {
        return new TrusteeType();
    }

    /**
     * Create an instance of {@link FileAccessRequestType }
     * 
     */
    public FileAccessRequestType createFileAccessRequestType() {
        return new FileAccessRequestType();
    }

    /**
     * Create an instance of {@link FileAccessesType }
     * 
     */
    public FileAccessesType createFileAccessesType() {
        return new FileAccessesType();
    }

    /**
     * Create an instance of {@link FileAccessType }
     * 
     */
    public FileAccessType createFileAccessType() {
        return new FileAccessType();
    }

    /**
     * Create an instance of {@link ScoreType.KeyContributingFactors }
     * 
     */
    public ScoreType.KeyContributingFactors createScoreTypeKeyContributingFactors() {
        return new ScoreType.KeyContributingFactors();
    }

    /**
     * Create an instance of {@link OrganisationType.Type }
     * 
     */
    public OrganisationType.Type createOrganisationTypeType() {
        return new OrganisationType.Type();
    }

    /**
     * Create an instance of {@link OrganisationType.Status }
     * 
     */
    public OrganisationType.Status createOrganisationTypeStatus() {
        return new OrganisationType.Status();
    }

    /**
     * Create an instance of {@link PublicRecordOrConsumerCreditInformationType.CourtActions }
     * 
     */
    public PublicRecordOrConsumerCreditInformationType.CourtActions createPublicRecordOrConsumerCreditInformationTypeCourtActions() {
        return new PublicRecordOrConsumerCreditInformationType.CourtActions();
    }

    /**
     * Create an instance of {@link PublicRecordOrConsumerCreditInformationType.DisqualifiedDirectorships }
     * 
     */
    public PublicRecordOrConsumerCreditInformationType.DisqualifiedDirectorships createPublicRecordOrConsumerCreditInformationTypeDisqualifiedDirectorships() {
        return new PublicRecordOrConsumerCreditInformationType.DisqualifiedDirectorships();
    }

    /**
     * Create an instance of {@link PublicRecordOrConsumerCreditInformationType.Directorships }
     * 
     */
    public PublicRecordOrConsumerCreditInformationType.Directorships createPublicRecordOrConsumerCreditInformationTypeDirectorships() {
        return new PublicRecordOrConsumerCreditInformationType.Directorships();
    }

    /**
     * Create an instance of {@link PublicRecordOrConsumerCreditInformationType.BusinessNames }
     * 
     */
    public PublicRecordOrConsumerCreditInformationType.BusinessNames createPublicRecordOrConsumerCreditInformationTypeBusinessNames() {
        return new PublicRecordOrConsumerCreditInformationType.BusinessNames();
    }

    /**
     * Create an instance of {@link PublicRecordOrConsumerCreditInformationType.PersonalInsolvencies }
     * 
     */
    public PublicRecordOrConsumerCreditInformationType.PersonalInsolvencies createPublicRecordOrConsumerCreditInformationTypePersonalInsolvencies() {
        return new PublicRecordOrConsumerCreditInformationType.PersonalInsolvencies();
    }

    /**
     * Create an instance of {@link PublicRecordOrConsumerCreditInformationType.SoleTrader }
     * 
     */
    public PublicRecordOrConsumerCreditInformationType.SoleTrader createPublicRecordOrConsumerCreditInformationTypeSoleTrader() {
        return new PublicRecordOrConsumerCreditInformationType.SoleTrader();
    }

    /**
     * Create an instance of {@link PossibleMatchesType.MatchCriteria }
     * 
     */
    public PossibleMatchesType.MatchCriteria createPossibleMatchesTypeMatchCriteria() {
        return new PossibleMatchesType.MatchCriteria();
    }

    /**
     * Create an instance of {@link PossibleMatchType.Addresses }
     * 
     */
    public PossibleMatchType.Addresses createPossibleMatchTypeAddresses() {
        return new PossibleMatchType.Addresses();
    }

    /**
     * Create an instance of {@link PossibleMatchType.Employment }
     * 
     */
    public PossibleMatchType.Employment createPossibleMatchTypeEmployment() {
        return new PossibleMatchType.Employment();
    }

    /**
     * Create an instance of {@link PersonalInsolvencyType.Type }
     * 
     */
    public PersonalInsolvencyType.Type createPersonalInsolvencyTypeType() {
        return new PersonalInsolvencyType.Type();
    }

    /**
     * Create an instance of {@link PersonalInsolvencyType.Status }
     * 
     */
    public PersonalInsolvencyType.Status createPersonalInsolvencyTypeStatus() {
        return new PersonalInsolvencyType.Status();
    }

    /**
     * Create an instance of {@link PersonalInsolvencyType.Relationship }
     * 
     */
    public PersonalInsolvencyType.Relationship createPersonalInsolvencyTypeRelationship() {
        return new PersonalInsolvencyType.Relationship();
    }

    /**
     * Create an instance of {@link IndividualInputEchoType.KnownAsNames }
     * 
     */
    public IndividualInputEchoType.KnownAsNames createIndividualInputEchoTypeKnownAsNames() {
        return new IndividualInputEchoType.KnownAsNames();
    }

    /**
     * Create an instance of {@link IndividualInputEchoType.PreviousNames }
     * 
     */
    public IndividualInputEchoType.PreviousNames createIndividualInputEchoTypePreviousNames() {
        return new IndividualInputEchoType.PreviousNames();
    }

    /**
     * Create an instance of {@link IndividualInputEchoType.Addresses }
     * 
     */
    public IndividualInputEchoType.Addresses createIndividualInputEchoTypeAddresses() {
        return new IndividualInputEchoType.Addresses();
    }

    /**
     * Create an instance of {@link IndividualInputEchoType.Gender }
     * 
     */
    public IndividualInputEchoType.Gender createIndividualInputEchoTypeGender() {
        return new IndividualInputEchoType.Gender();
    }

    /**
     * Create an instance of {@link IndividualInputEchoType.Employment }
     * 
     */
    public IndividualInputEchoType.Employment createIndividualInputEchoTypeEmployment() {
        return new IndividualInputEchoType.Employment();
    }

    /**
     * Create an instance of {@link IndividualInputStrictType.KnownAsNames }
     * 
     */
    public IndividualInputStrictType.KnownAsNames createIndividualInputStrictTypeKnownAsNames() {
        return new IndividualInputStrictType.KnownAsNames();
    }

    /**
     * Create an instance of {@link IndividualInputStrictType.PreviousNames }
     * 
     */
    public IndividualInputStrictType.PreviousNames createIndividualInputStrictTypePreviousNames() {
        return new IndividualInputStrictType.PreviousNames();
    }

    /**
     * Create an instance of {@link IndividualInputStrictType.Addresses }
     * 
     */
    public IndividualInputStrictType.Addresses createIndividualInputStrictTypeAddresses() {
        return new IndividualInputStrictType.Addresses();
    }

    /**
     * Create an instance of {@link IndividualInputStrictType.Employment }
     * 
     */
    public IndividualInputStrictType.Employment createIndividualInputStrictTypeEmployment() {
        return new IndividualInputStrictType.Employment();
    }

    /**
     * Create an instance of {@link IndividualInputType.KnownAsNames }
     * 
     */
    public IndividualInputType.KnownAsNames createIndividualInputTypeKnownAsNames() {
        return new IndividualInputType.KnownAsNames();
    }

    /**
     * Create an instance of {@link IndividualInputType.PreviousNames }
     * 
     */
    public IndividualInputType.PreviousNames createIndividualInputTypePreviousNames() {
        return new IndividualInputType.PreviousNames();
    }

    /**
     * Create an instance of {@link IndividualInputType.Addresses }
     * 
     */
    public IndividualInputType.Addresses createIndividualInputTypeAddresses() {
        return new IndividualInputType.Addresses();
    }

    /**
     * Create an instance of {@link IndividualInputType.Employment }
     * 
     */
    public IndividualInputType.Employment createIndividualInputTypeEmployment() {
        return new IndividualInputType.Employment();
    }

    /**
     * Create an instance of {@link IdentityType.IndividualName }
     * 
     */
    public IdentityType.IndividualName createIdentityTypeIndividualName() {
        return new IdentityType.IndividualName();
    }

    /**
     * Create an instance of {@link IdentityType.Gender }
     * 
     */
    public IdentityType.Gender createIdentityTypeGender() {
        return new IdentityType.Gender();
    }

    /**
     * Create an instance of {@link IdentityType.DateOfBirth }
     * 
     */
    public IdentityType.DateOfBirth createIdentityTypeDateOfBirth() {
        return new IdentityType.DateOfBirth();
    }

    /**
     * Create an instance of {@link IdentityType.DriversLicence }
     * 
     */
    public IdentityType.DriversLicence createIdentityTypeDriversLicence() {
        return new IdentityType.DriversLicence();
    }

    /**
     * Create an instance of {@link IdentityType.LodgedComplaint }
     * 
     */
    public IdentityType.LodgedComplaint createIdentityTypeLodgedComplaint() {
        return new IdentityType.LodgedComplaint();
    }

    /**
     * Create an instance of {@link IdentityType.IsDeceased }
     * 
     */
    public IdentityType.IsDeceased createIdentityTypeIsDeceased() {
        return new IdentityType.IsDeceased();
    }

    /**
     * Create an instance of {@link IdentityType.DoNotProvideCredit }
     * 
     */
    public IdentityType.DoNotProvideCredit createIdentityTypeDoNotProvideCredit() {
        return new IdentityType.DoNotProvideCredit();
    }

    /**
     * Create an instance of {@link IdentityType.OtherIndicators.Indicator }
     * 
     */
    public IdentityType.OtherIndicators.Indicator createIdentityTypeOtherIndicatorsIndicator() {
        return new IdentityType.OtherIndicators.Indicator();
    }

    /**
     * Create an instance of {@link KeyValuePairType.Value }
     * 
     */
    public KeyValuePairType.Value createKeyValuePairTypeValue() {
        return new KeyValuePairType.Value();
    }

    /**
     * Create an instance of {@link EventType.EventDetails.Property.PriorValue }
     * 
     */
    public EventType.EventDetails.Property.PriorValue createEventTypeEventDetailsPropertyPriorValue() {
        return new EventType.EventDetails.Property.PriorValue();
    }

    /**
     * Create an instance of {@link EventType.EventDetails.Property.UpdatedValue }
     * 
     */
    public EventType.EventDetails.Property.UpdatedValue createEventTypeEventDetailsPropertyUpdatedValue() {
        return new EventType.EventDetails.Property.UpdatedValue();
    }

    /**
     * Create an instance of {@link EnquiryReportType.PrimaryMatch }
     * 
     */
    public EnquiryReportType.PrimaryMatch createEnquiryReportTypePrimaryMatch() {
        return new EnquiryReportType.PrimaryMatch();
    }

    /**
     * Create an instance of {@link EnquiryReportType.Addresses }
     * 
     */
    public EnquiryReportType.Addresses createEnquiryReportTypeAddresses() {
        return new EnquiryReportType.Addresses();
    }

    /**
     * Create an instance of {@link EnquiryReportType.Employment }
     * 
     */
    public EnquiryReportType.Employment createEnquiryReportTypeEmployment() {
        return new EnquiryReportType.Employment();
    }

    /**
     * Create an instance of {@link EnquiryReportType.OtherIdentities.OtherIdentity }
     * 
     */
    public EnquiryReportType.OtherIdentities.OtherIdentity createEnquiryReportTypeOtherIdentitiesOtherIdentity() {
        return new EnquiryReportType.OtherIdentities.OtherIdentity();
    }

    /**
     * Create an instance of {@link EnquiryType.OtherEnquiryAttributes }
     * 
     */
    public EnquiryType.OtherEnquiryAttributes createEnquiryTypeOtherEnquiryAttributes() {
        return new EnquiryType.OtherEnquiryAttributes();
    }

    /**
     * Create an instance of {@link CommercialDefaultRecordType.ReasonToReport }
     * 
     */
    public CommercialDefaultRecordType.ReasonToReport createCommercialDefaultRecordTypeReasonToReport() {
        return new CommercialDefaultRecordType.ReasonToReport();
    }

    /**
     * Create an instance of {@link CommercialDefaultType.Status }
     * 
     */
    public CommercialDefaultType.Status createCommercialDefaultTypeStatus() {
        return new CommercialDefaultType.Status();
    }

    /**
     * Create an instance of {@link ConsumerDefaultType.Status }
     * 
     */
    public ConsumerDefaultType.Status createConsumerDefaultTypeStatus() {
        return new ConsumerDefaultType.Status();
    }

    /**
     * Create an instance of {@link CreditEnquiryType.AccountType }
     * 
     */
    public CreditEnquiryType.AccountType createCreditEnquiryTypeAccountType() {
        return new CreditEnquiryType.AccountType();
    }

    /**
     * Create an instance of {@link CreditEnquiryType.SecuredCredit }
     * 
     */
    public CreditEnquiryType.SecuredCredit createCreditEnquiryTypeSecuredCredit() {
        return new CreditEnquiryType.SecuredCredit();
    }

    /**
     * Create an instance of {@link CreditEnquiryType.Relationship }
     * 
     */
    public CreditEnquiryType.Relationship createCreditEnquiryTypeRelationship() {
        return new CreditEnquiryType.Relationship();
    }

    /**
     * Create an instance of {@link CreditEnquiryType.CreditEnquirer }
     * 
     */
    public CreditEnquiryType.CreditEnquirer createCreditEnquiryTypeCreditEnquirer() {
        return new CreditEnquiryType.CreditEnquirer();
    }

    /**
     * Create an instance of {@link CourtActionType.Relationship }
     * 
     */
    public CourtActionType.Relationship createCourtActionTypeRelationship() {
        return new CourtActionType.Relationship();
    }

    /**
     * Create an instance of {@link CourtActionType.CourtActionStatus }
     * 
     */
    public CourtActionType.CourtActionStatus createCourtActionTypeCourtActionStatus() {
        return new CourtActionType.CourtActionStatus();
    }

    /**
     * Create an instance of {@link CommercialCreditAccountType.AccountType }
     * 
     */
    public CommercialCreditAccountType.AccountType createCommercialCreditAccountTypeAccountType() {
        return new CommercialCreditAccountType.AccountType();
    }

    /**
     * Create an instance of {@link CommercialCreditAccountType.Relationship }
     * 
     */
    public CommercialCreditAccountType.Relationship createCommercialCreditAccountTypeRelationship() {
        return new CommercialCreditAccountType.Relationship();
    }

    /**
     * Create an instance of {@link CommercialCreditAccountType.LoanPaymentMethod }
     * 
     */
    public CommercialCreditAccountType.LoanPaymentMethod createCommercialCreditAccountTypeLoanPaymentMethod() {
        return new CommercialCreditAccountType.LoanPaymentMethod();
    }

    /**
     * Create an instance of {@link CommercialCreditAccountType.TermType }
     * 
     */
    public CommercialCreditAccountType.TermType createCommercialCreditAccountTypeTermType() {
        return new CommercialCreditAccountType.TermType();
    }

    /**
     * Create an instance of {@link CommercialCreditAccountType.SecuredCredit }
     * 
     */
    public CommercialCreditAccountType.SecuredCredit createCommercialCreditAccountTypeSecuredCredit() {
        return new CommercialCreditAccountType.SecuredCredit();
    }

    /**
     * Create an instance of {@link CommercialCreditAccountType.LatestMaximumAmountCredit }
     * 
     */
    public CommercialCreditAccountType.LatestMaximumAmountCredit createCommercialCreditAccountTypeLatestMaximumAmountCredit() {
        return new CommercialCreditAccountType.LatestMaximumAmountCredit();
    }

    /**
     * Create an instance of {@link CommercialCreditAccountType.RepaymentHistory }
     * 
     */
    public CommercialCreditAccountType.RepaymentHistory createCommercialCreditAccountTypeRepaymentHistory() {
        return new CommercialCreditAccountType.RepaymentHistory();
    }

    /**
     * Create an instance of {@link CommercialCreditAccountType.Defaults }
     * 
     */
    public CommercialCreditAccountType.Defaults createCommercialCreditAccountTypeDefaults() {
        return new CommercialCreditAccountType.Defaults();
    }

    /**
     * Create an instance of {@link CommercialCreditAccountType.AccountHistory }
     * 
     */
    public CommercialCreditAccountType.AccountHistory createCommercialCreditAccountTypeAccountHistory() {
        return new CommercialCreditAccountType.AccountHistory();
    }

    /**
     * Create an instance of {@link CommercialCreditAccountType.LatestCreditProvider.TransferReason }
     * 
     */
    public CommercialCreditAccountType.LatestCreditProvider.TransferReason createCommercialCreditAccountTypeLatestCreditProviderTransferReason() {
        return new CommercialCreditAccountType.LatestCreditProvider.TransferReason();
    }

    /**
     * Create an instance of {@link ConsumerCreditAccountType.AccountType }
     * 
     */
    public ConsumerCreditAccountType.AccountType createConsumerCreditAccountTypeAccountType() {
        return new ConsumerCreditAccountType.AccountType();
    }

    /**
     * Create an instance of {@link ConsumerCreditAccountType.Relationship }
     * 
     */
    public ConsumerCreditAccountType.Relationship createConsumerCreditAccountTypeRelationship() {
        return new ConsumerCreditAccountType.Relationship();
    }

    /**
     * Create an instance of {@link ConsumerCreditAccountType.LoanPaymentMethod }
     * 
     */
    public ConsumerCreditAccountType.LoanPaymentMethod createConsumerCreditAccountTypeLoanPaymentMethod() {
        return new ConsumerCreditAccountType.LoanPaymentMethod();
    }

    /**
     * Create an instance of {@link ConsumerCreditAccountType.TermType }
     * 
     */
    public ConsumerCreditAccountType.TermType createConsumerCreditAccountTypeTermType() {
        return new ConsumerCreditAccountType.TermType();
    }

    /**
     * Create an instance of {@link ConsumerCreditAccountType.SecuredCredit }
     * 
     */
    public ConsumerCreditAccountType.SecuredCredit createConsumerCreditAccountTypeSecuredCredit() {
        return new ConsumerCreditAccountType.SecuredCredit();
    }

    /**
     * Create an instance of {@link ConsumerCreditAccountType.LatestMaximumAmountCredit }
     * 
     */
    public ConsumerCreditAccountType.LatestMaximumAmountCredit createConsumerCreditAccountTypeLatestMaximumAmountCredit() {
        return new ConsumerCreditAccountType.LatestMaximumAmountCredit();
    }

    /**
     * Create an instance of {@link ConsumerCreditAccountType.RepaymentHistory }
     * 
     */
    public ConsumerCreditAccountType.RepaymentHistory createConsumerCreditAccountTypeRepaymentHistory() {
        return new ConsumerCreditAccountType.RepaymentHistory();
    }

    /**
     * Create an instance of {@link ConsumerCreditAccountType.Defaults }
     * 
     */
    public ConsumerCreditAccountType.Defaults createConsumerCreditAccountTypeDefaults() {
        return new ConsumerCreditAccountType.Defaults();
    }

    /**
     * Create an instance of {@link ConsumerCreditAccountType.AccountHistory }
     * 
     */
    public ConsumerCreditAccountType.AccountHistory createConsumerCreditAccountTypeAccountHistory() {
        return new ConsumerCreditAccountType.AccountHistory();
    }

    /**
     * Create an instance of {@link ConsumerCreditAccountType.LatestCreditProvider.TransferReason }
     * 
     */
    public ConsumerCreditAccountType.LatestCreditProvider.TransferReason createConsumerCreditAccountTypeLatestCreditProviderTransferReason() {
        return new ConsumerCreditAccountType.LatestCreditProvider.TransferReason();
    }

    /**
     * Create an instance of {@link ContributingFactorType.ScoreImpactor }
     * 
     */
    public ContributingFactorType.ScoreImpactor createContributingFactorTypeScoreImpactor() {
        return new ContributingFactorType.ScoreImpactor();
    }

    /**
     * Create an instance of {@link ConsumerCreditFileType.FileNotes }
     * 
     */
    public ConsumerCreditFileType.FileNotes createConsumerCreditFileTypeFileNotes() {
        return new ConsumerCreditFileType.FileNotes();
    }

    /**
     * Create an instance of {@link ConsumerCreditFileType.CreditEnquiries }
     * 
     */
    public ConsumerCreditFileType.CreditEnquiries createConsumerCreditFileTypeCreditEnquiries() {
        return new ConsumerCreditFileType.CreditEnquiries();
    }

    /**
     * Create an instance of {@link ConsumerCreditFileType.Accounts }
     * 
     */
    public ConsumerCreditFileType.Accounts createConsumerCreditFileTypeAccounts() {
        return new ConsumerCreditFileType.Accounts();
    }

    /**
     * Create an instance of {@link CommercialCreditFileType.FileNotes }
     * 
     */
    public CommercialCreditFileType.FileNotes createCommercialCreditFileTypeFileNotes() {
        return new CommercialCreditFileType.FileNotes();
    }

    /**
     * Create an instance of {@link CommercialCreditFileType.CreditEnquiries }
     * 
     */
    public CommercialCreditFileType.CreditEnquiries createCommercialCreditFileTypeCreditEnquiries() {
        return new CommercialCreditFileType.CreditEnquiries();
    }

    /**
     * Create an instance of {@link CommercialCreditFileType.Accounts }
     * 
     */
    public CommercialCreditFileType.Accounts createCommercialCreditFileTypeAccounts() {
        return new CommercialCreditFileType.Accounts();
    }

    /**
     * Create an instance of {@link CharacteristicType.Value }
     * 
     */
    public CharacteristicType.Value createCharacteristicTypeValue() {
        return new CharacteristicType.Value();
    }

    /**
     * Create an instance of {@link BusinessNameType.Business }
     * 
     */
    public BusinessNameType.Business createBusinessNameTypeBusiness() {
        return new BusinessNameType.Business();
    }

    /**
     * Create an instance of {@link TicketResponseType.GeneralMessages.Message }
     * 
     */
    public TicketResponseType.GeneralMessages.Message createTicketResponseTypeGeneralMessagesMessage() {
        return new TicketResponseType.GeneralMessages.Message();
    }

    /**
     * Create an instance of {@link MessagesType.Message }
     * 
     */
    public MessagesType.Message createMessagesTypeMessage() {
        return new MessagesType.Message();
    }

    /**
     * Create an instance of {@link ResponseType.ProductData.SummaryData }
     * 
     */
    public ResponseType.ProductData.SummaryData createResponseTypeProductDataSummaryData() {
        return new ResponseType.ProductData.SummaryData();
    }

    /**
     * Create an instance of {@link ResponseType.ProductData.ScoreData }
     * 
     */
    public ResponseType.ProductData.ScoreData createResponseTypeProductDataScoreData() {
        return new ResponseType.ProductData.ScoreData();
    }

    /**
     * Create an instance of {@link ResponseType.ProductData.PossibleMatches }
     * 
     */
    public ResponseType.ProductData.PossibleMatches createResponseTypeProductDataPossibleMatches() {
        return new ResponseType.ProductData.PossibleMatches();
    }

    /**
     * Create an instance of {@link ProductHeaderType.PermissionType }
     * 
     */
    public ProductHeaderType.PermissionType createProductHeaderTypePermissionType() {
        return new ProductHeaderType.PermissionType();
    }

    /**
     * Create an instance of {@link ProductHeaderType.ProductDataLevel }
     * 
     */
    public ProductHeaderType.ProductDataLevel createProductHeaderTypeProductDataLevel() {
        return new ProductHeaderType.ProductDataLevel();
    }

    /**
     * Create an instance of {@link ProductHeaderType.CustomInputParameters }
     * 
     */
    public ProductHeaderType.CustomInputParameters createProductHeaderTypeCustomInputParameters() {
        return new ProductHeaderType.CustomInputParameters();
    }

    /**
     * Create an instance of {@link ProductHeaderType.ConfigurationDataAttributes }
     * 
     */
    public ProductHeaderType.ConfigurationDataAttributes createProductHeaderTypeConfigurationDataAttributes() {
        return new ProductHeaderType.ConfigurationDataAttributes();
    }

    /**
     * Create an instance of {@link RequestType.EnquiryData }
     * 
     */
    public RequestType.EnquiryData createRequestTypeEnquiryData() {
        return new RequestType.EnquiryData();
    }

    /**
     * Create an instance of {@link RequestType.EnquiryHeader.RequestedScores }
     * 
     */
    public RequestType.EnquiryHeader.RequestedScores createRequestTypeEnquiryHeaderRequestedScores() {
        return new RequestType.EnquiryHeader.RequestedScores();
    }

    /**
     * Create an instance of {@link RequestType.EnquiryHeader.CustomInputParameters }
     * 
     */
    public RequestType.EnquiryHeader.CustomInputParameters createRequestTypeEnquiryHeaderCustomInputParameters() {
        return new RequestType.EnquiryHeader.CustomInputParameters();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd", name = "request")
    public JAXBElement<RequestType> createRequest(RequestType value) {
        return new JAXBElement<RequestType>(_Request_QNAME, RequestType.class, null, value);
    }

}
