//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 04:23:17 PM IST 
//


package ConsumerFinancing.equifax.models.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * Summary details of organisation/business
 * 
 * <p>Java class for organisationSummaryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="organisationSummaryType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="enquiries" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="payment-defaults" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="mercantile" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="court-writs" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="court-actions" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="current-directors" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="previous-directors" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="proprietorships" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="charges" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="petitions" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *         &lt;element name="default-judgments" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "organisationSummaryType", propOrder = {
    "enquiries",
    "paymentDefaults",
    "mercantile",
    "courtWrits",
    "courtActions",
    "currentDirectors",
    "previousDirectors",
    "proprietorships",
    "charges",
    "petitions",
    "defaultJudgments"
})
public class OrganisationSummaryType {

    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String enquiries;
    @XmlElement(name = "payment-defaults")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String paymentDefaults;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String mercantile;
    @XmlElement(name = "court-writs")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String courtWrits;
    @XmlElement(name = "court-actions")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String courtActions;
    @XmlElement(name = "current-directors")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String currentDirectors;
    @XmlElement(name = "previous-directors")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String previousDirectors;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String proprietorships;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String charges;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String petitions;
    @XmlElement(name = "default-judgments")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String defaultJudgments;

    /**
     * Gets the value of the enquiries property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnquiries() {
        return enquiries;
    }

    /**
     * Sets the value of the enquiries property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnquiries(String value) {
        this.enquiries = value;
    }

    /**
     * Gets the value of the paymentDefaults property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaymentDefaults() {
        return paymentDefaults;
    }

    /**
     * Sets the value of the paymentDefaults property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaymentDefaults(String value) {
        this.paymentDefaults = value;
    }

    /**
     * Gets the value of the mercantile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMercantile() {
        return mercantile;
    }

    /**
     * Sets the value of the mercantile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMercantile(String value) {
        this.mercantile = value;
    }

    /**
     * Gets the value of the courtWrits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourtWrits() {
        return courtWrits;
    }

    /**
     * Sets the value of the courtWrits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourtWrits(String value) {
        this.courtWrits = value;
    }

    /**
     * Gets the value of the courtActions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourtActions() {
        return courtActions;
    }

    /**
     * Sets the value of the courtActions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourtActions(String value) {
        this.courtActions = value;
    }

    /**
     * Gets the value of the currentDirectors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentDirectors() {
        return currentDirectors;
    }

    /**
     * Sets the value of the currentDirectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentDirectors(String value) {
        this.currentDirectors = value;
    }

    /**
     * Gets the value of the previousDirectors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreviousDirectors() {
        return previousDirectors;
    }

    /**
     * Sets the value of the previousDirectors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreviousDirectors(String value) {
        this.previousDirectors = value;
    }

    /**
     * Gets the value of the proprietorships property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProprietorships() {
        return proprietorships;
    }

    /**
     * Sets the value of the proprietorships property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProprietorships(String value) {
        this.proprietorships = value;
    }

    /**
     * Gets the value of the charges property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharges() {
        return charges;
    }

    /**
     * Sets the value of the charges property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharges(String value) {
        this.charges = value;
    }

    /**
     * Gets the value of the petitions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPetitions() {
        return petitions;
    }

    /**
     * Sets the value of the petitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPetitions(String value) {
        this.petitions = value;
    }

    /**
     * Gets the value of the defaultJudgments property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultJudgments() {
        return defaultJudgments;
    }

    /**
     * Sets the value of the defaultJudgments property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultJudgments(String value) {
        this.defaultJudgments = value;
    }

}
