//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 04:23:17 PM IST 
//


package ConsumerFinancing.equifax.models.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for requestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="requestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="enquiry-header"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="client-reference" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *                   &lt;element name="operator-id" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *                   &lt;element name="operator-name" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
 *                   &lt;element name="permission-type-code" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *                   &lt;element name="product-data-level-code" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *                   &lt;element name="requested-scores" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="scorecard-id" type="{http://www.w3.org/2001/XMLSchema}token" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="possible-matches" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}possible-matchesType" minOccurs="0"/&gt;
 *                   &lt;element name="custom-input-parameters" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="custom-input-parameter" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}key-value-pairType" maxOccurs="unbounded"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="enquiry-data"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;choice&gt;
 *                     &lt;element name="bureau-reference" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}BureauReferenceSimpleType"/&gt;
 *                     &lt;element name="individual" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}individual-inputType"/&gt;
 *                   &lt;/choice&gt;
 *                   &lt;element name="enquiry" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}enquiryType" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "requestType", propOrder = {
    "enquiryHeader",
    "enquiryData"
})
@XmlRootElement
public class RequestType {

    @XmlElement(name = "enquiry-header", required = true)
    protected RequestType.EnquiryHeader enquiryHeader;
    @XmlElement(name = "enquiry-data", required = true)
    protected RequestType.EnquiryData enquiryData;

    /**
     * Gets the value of the enquiryHeader property.
     * 
     * @return
     *     possible object is
     *     {@link RequestType.EnquiryHeader }
     *     
     */
    public RequestType.EnquiryHeader getEnquiryHeader() {
        return enquiryHeader;
    }

    /**
     * Sets the value of the enquiryHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestType.EnquiryHeader }
     *     
     */
    public void setEnquiryHeader(RequestType.EnquiryHeader value) {
        this.enquiryHeader = value;
    }

    /**
     * Gets the value of the enquiryData property.
     * 
     * @return
     *     possible object is
     *     {@link RequestType.EnquiryData }
     *     
     */
    public RequestType.EnquiryData getEnquiryData() {
        return enquiryData;
    }

    /**
     * Sets the value of the enquiryData property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestType.EnquiryData }
     *     
     */
    public void setEnquiryData(RequestType.EnquiryData value) {
        this.enquiryData = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;choice&gt;
     *           &lt;element name="bureau-reference" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}BureauReferenceSimpleType"/&gt;
     *           &lt;element name="individual" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}individual-inputType"/&gt;
     *         &lt;/choice&gt;
     *         &lt;element name="enquiry" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}enquiryType" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bureauReference",
        "individual",
        "enquiry"
    })
    public static class EnquiryData {

        @XmlElement(name = "bureau-reference")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String bureauReference;
        protected IndividualInputType individual;
        protected EnquiryType enquiry;

        /**
         * Gets the value of the bureauReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBureauReference() {
            return bureauReference;
        }

        /**
         * Sets the value of the bureauReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBureauReference(String value) {
            this.bureauReference = value;
        }

        /**
         * Gets the value of the individual property.
         * 
         * @return
         *     possible object is
         *     {@link IndividualInputType }
         *     
         */
        public IndividualInputType getIndividual() {
            return individual;
        }

        /**
         * Sets the value of the individual property.
         * 
         * @param value
         *     allowed object is
         *     {@link IndividualInputType }
         *     
         */
        public void setIndividual(IndividualInputType value) {
            this.individual = value;
        }

        /**
         * Gets the value of the enquiry property.
         * 
         * @return
         *     possible object is
         *     {@link EnquiryType }
         *     
         */
        public EnquiryType getEnquiry() {
            return enquiry;
        }

        /**
         * Sets the value of the enquiry property.
         * 
         * @param value
         *     allowed object is
         *     {@link EnquiryType }
         *     
         */
        public void setEnquiry(EnquiryType value) {
            this.enquiry = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="client-reference" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
     *         &lt;element name="operator-id" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
     *         &lt;element name="operator-name" type="{http://www.w3.org/2001/XMLSchema}token" minOccurs="0"/&gt;
     *         &lt;element name="permission-type-code" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
     *         &lt;element name="product-data-level-code" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
     *         &lt;element name="requested-scores" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="scorecard-id" type="{http://www.w3.org/2001/XMLSchema}token" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="possible-matches" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}possible-matchesType" minOccurs="0"/&gt;
     *         &lt;element name="custom-input-parameters" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="custom-input-parameter" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}key-value-pairType" maxOccurs="unbounded"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "clientReference",
        "operatorId",
        "operatorName",
        "permissionTypeCode",
        "productDataLevelCode",
        "requestedScores",
        "possibleMatches",
        "customInputParameters"
    })
    public static class EnquiryHeader {

        @XmlElement(name = "client-reference")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String clientReference;
        @XmlElement(name = "operator-id")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String operatorId;
        @XmlElement(name = "operator-name")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String operatorName;
        @XmlElement(name = "permission-type-code", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String permissionTypeCode;
        @XmlElement(name = "product-data-level-code", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String productDataLevelCode;
        @XmlElement(name = "requested-scores")
        protected RequestType.EnquiryHeader.RequestedScores requestedScores;
        @XmlElement(name = "possible-matches")
        protected PossibleMatchesType possibleMatches;
        @XmlElement(name = "custom-input-parameters")
        protected RequestType.EnquiryHeader.CustomInputParameters customInputParameters;

        /**
         * Gets the value of the clientReference property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClientReference() {
            return clientReference;
        }

        /**
         * Sets the value of the clientReference property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClientReference(String value) {
            this.clientReference = value;
        }

        /**
         * Gets the value of the operatorId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOperatorId() {
            return operatorId;
        }

        /**
         * Sets the value of the operatorId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOperatorId(String value) {
            this.operatorId = value;
        }

        /**
         * Gets the value of the operatorName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOperatorName() {
            return operatorName;
        }

        /**
         * Sets the value of the operatorName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOperatorName(String value) {
            this.operatorName = value;
        }

        /**
         * Gets the value of the permissionTypeCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPermissionTypeCode() {
            return permissionTypeCode;
        }

        /**
         * Sets the value of the permissionTypeCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPermissionTypeCode(String value) {
            this.permissionTypeCode = value;
        }

        /**
         * Gets the value of the productDataLevelCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProductDataLevelCode() {
            return productDataLevelCode;
        }

        /**
         * Sets the value of the productDataLevelCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProductDataLevelCode(String value) {
            this.productDataLevelCode = value;
        }

        /**
         * Gets the value of the requestedScores property.
         * 
         * @return
         *     possible object is
         *     {@link RequestType.EnquiryHeader.RequestedScores }
         *     
         */
        public RequestType.EnquiryHeader.RequestedScores getRequestedScores() {
            return requestedScores;
        }

        /**
         * Sets the value of the requestedScores property.
         * 
         * @param value
         *     allowed object is
         *     {@link RequestType.EnquiryHeader.RequestedScores }
         *     
         */
        public void setRequestedScores(RequestType.EnquiryHeader.RequestedScores value) {
            this.requestedScores = value;
        }

        /**
         * Gets the value of the possibleMatches property.
         * 
         * @return
         *     possible object is
         *     {@link PossibleMatchesType }
         *     
         */
        public PossibleMatchesType getPossibleMatches() {
            return possibleMatches;
        }

        /**
         * Sets the value of the possibleMatches property.
         * 
         * @param value
         *     allowed object is
         *     {@link PossibleMatchesType }
         *     
         */
        public void setPossibleMatches(PossibleMatchesType value) {
            this.possibleMatches = value;
        }

        /**
         * Gets the value of the customInputParameters property.
         * 
         * @return
         *     possible object is
         *     {@link RequestType.EnquiryHeader.CustomInputParameters }
         *     
         */
        public RequestType.EnquiryHeader.CustomInputParameters getCustomInputParameters() {
            return customInputParameters;
        }

        /**
         * Sets the value of the customInputParameters property.
         * 
         * @param value
         *     allowed object is
         *     {@link RequestType.EnquiryHeader.CustomInputParameters }
         *     
         */
        public void setCustomInputParameters(RequestType.EnquiryHeader.CustomInputParameters value) {
            this.customInputParameters = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="custom-input-parameter" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}key-value-pairType" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "customInputParameter"
        })
        public static class CustomInputParameters {

            @XmlElement(name = "custom-input-parameter", required = true)
            protected List<KeyValuePairType> customInputParameter;

            /**
             * Gets the value of the customInputParameter property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the customInputParameter property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getCustomInputParameter().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link KeyValuePairType }
             * 
             * 
             */
            public List<KeyValuePairType> getCustomInputParameter() {
                if (customInputParameter == null) {
                    customInputParameter = new ArrayList<KeyValuePairType>();
                }
                return this.customInputParameter;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="scorecard-id" type="{http://www.w3.org/2001/XMLSchema}token" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "scorecardId"
        })
        public static class RequestedScores {

            @XmlElement(name = "scorecard-id", required = true)
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            @XmlSchemaType(name = "token")
            protected List<String> scorecardId;

            /**
             * Gets the value of the scorecardId property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the scorecardId property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getScorecardId().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link String }
             * 
             * 
             */
            public List<String> getScorecardId() {
                if (scorecardId == null) {
                    scorecardId = new ArrayList<String>();
                }
                return scorecardId;
            }

            public void setScorecardId(List<String> scorecardId) {
                this.scorecardId = scorecardId;
            }
        }

    }

}
