//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.11.24 at 04:23:17 PM IST 
//


package ConsumerFinancing.equifax.models.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for sole-trader-registrationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="sole-trader-registrationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id-references" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}IdReferencesType" minOccurs="0"/&gt;
 *         &lt;element name="ABN" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}ABNSimpleType" minOccurs="0"/&gt;
 *         &lt;element name="additional-fields" type="{http://vedaxml.com/vxml2/vedascore-apply-v2-0.xsd}additional-data-fieldsType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sole-trader-registrationType", propOrder = {
    "idReferences",
    "abn",
    "additionalFields"
})
public class SoleTraderRegistrationType {

    @XmlElement(name = "id-references")
    protected IdReferencesType idReferences;
    @XmlElement(name = "ABN")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String abn;
    @XmlElement(name = "additional-fields")
    protected AdditionalDataFieldsType additionalFields;

    /**
     * Gets the value of the idReferences property.
     * 
     * @return
     *     possible object is
     *     {@link IdReferencesType }
     *     
     */
    public IdReferencesType getIdReferences() {
        return idReferences;
    }

    /**
     * Sets the value of the idReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdReferencesType }
     *     
     */
    public void setIdReferences(IdReferencesType value) {
        this.idReferences = value;
    }

    /**
     * Gets the value of the abn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getABN() {
        return abn;
    }

    /**
     * Sets the value of the abn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setABN(String value) {
        this.abn = value;
    }

    /**
     * Gets the value of the additionalFields property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalDataFieldsType }
     *     
     */
    public AdditionalDataFieldsType getAdditionalFields() {
        return additionalFields;
    }

    /**
     * Sets the value of the additionalFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalDataFieldsType }
     *     
     */
    public void setAdditionalFields(AdditionalDataFieldsType value) {
        this.additionalFields = value;
    }

}
